# -*- coding: utf-8 -*-
"""生成命令数据集 data/commands.json 与 data/commands.js

数据来源：
- Linux 命令：linux-commands-cheatsheet.pdf（Linuxize）提取的常用命令集，并补充分类扩展
- Git 命令：progit.pdf（Pro Git 官方手册）文档化的命令范围
命令均含中文说明、频率（高/中/低）、难度（入门/日常/进阶）、中文关键词、使用案例，
高频/易错命令额外含 pitfalls（易错警告）与 compare（命令对比）。
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
from command_options import OPTIONS  # noqa: E402
from command_intros import INTROS, PITFALLS, COMPARES  # noqa: E402
from command_outputs import OUTPUTS  # noqa: E402

ROOT = os.path.dirname(HERE)
DATA_DIR = os.path.join(ROOT, "data")
os.makedirs(DATA_DIR, exist_ok=True)

# 分类：group 用于区分 Linux / Git 两大体系
CATEGORIES = [
    {"id": "file", "name": "文件与目录操作", "group": "linux"},
    {"id": "view", "name": "文件查看", "group": "linux"},
    {"id": "text", "name": "文本处理", "group": "linux"},
    {"id": "perm", "name": "文件权限与属性", "group": "linux"},
    {"id": "user", "name": "用户与用户组", "group": "linux"},
    {"id": "proc", "name": "进程管理", "group": "linux"},
    {"id": "disk", "name": "磁盘与文件系统", "group": "linux"},
    {"id": "net", "name": "网络", "group": "linux"},
    {"id": "archive", "name": "压缩与归档", "group": "linux"},
    {"id": "sys", "name": "系统信息与监控", "group": "linux"},
    {"id": "power", "name": "关机与系统控制", "group": "linux"},
    {"id": "pkg", "name": "软件包管理", "group": "linux"},
    {"id": "kernel", "name": "内核模块", "group": "linux"},
    {"id": "shell", "name": "Shell 内建命令", "group": "linux"},
    {"id": "editor", "name": "编辑器与工具", "group": "linux"},
    {"id": "vim", "name": "Vim 编辑器", "group": "linux"},
    {"id": "g_config", "name": "仓库与配置", "group": "git"},
    {"id": "g_commit", "name": "暂存与提交", "group": "git"},
    {"id": "g_view", "name": "查看与比较", "group": "git"},
    {"id": "g_branch", "name": "分支与合并", "group": "git"},
    {"id": "g_remote", "name": "远程协作", "group": "git"},
    {"id": "g_undo", "name": "撤销与重置", "group": "git"},
    {"id": "g_patch", "name": "补丁与邮件", "group": "git"},
    {"id": "g_debug", "name": "调试", "group": "git"},
    {"id": "g_maint", "name": "维护", "group": "git"},
    {"id": "g_other", "name": "脚本与其他", "group": "git"},
    {"id": "g_plumb", "name": "底层命令 plumbing", "group": "git"},
    {"id": "g_adv", "name": "进阶工作流", "group": "git"},
    {"id": "g_transport", "name": "传输与服务", "group": "git"},
]


def c(name, cat, desc, kws, ex, freq, diff, pit=None, cmp=None):
    opts = OPTIONS.get(name)
    samp = OUTPUTS.get(name)
    return {
        "name": name,
        "category": cat,
        "description": INTROS.get(name, desc),
        "keywords": kws,
        "examples": [{"cmd": e[0], "desc": e[1]} for e in ex],
        "frequency": freq,
        "difficulty": diff,
        "pitfalls": pit if pit is not None else PITFALLS.get(name),
        "compare": cmp if cmp is not None else COMPARES.get(name),
        "options": [
            {"flag": o[0], "default": o[1], "desc": o[2]} for o in opts
        ] if opts else None,
        "sample": (
            {"output": samp[0], "explain": samp[1]} if samp else None
        ),
    }


LINUX = [
    # ---- 文件与目录操作 ----
    c("ls", "file", "列出目录内容", ["列出", "目录", "文件列表", "ls"],
      [("ls -la", "长格式显示全部文件（含隐藏文件）"), ("ls -lh", "以人类可读大小显示")], "高", "入门",
      "默认不显示隐藏文件（以 . 开头），需加 -a", "ls 列目录；ll 多为 ls -l 别名"),
    c("cd", "file", "切换工作目录", ["切换", "目录", "cd"],
      [("cd ~", "回到家目录"), ("cd -", "回到上次所在目录")], "高", "入门"),
    c("pwd", "file", "显示当前目录绝对路径", ["当前目录", "路径", "pwd"],
      [("pwd", "打印工作目录"), ("pwd -P", "解析符号链接后的真实路径")], "高", "入门"),
    c("cp", "file", "复制文件或目录", ["复制", "拷贝", "cp"],
      [("cp a.txt b.txt", "复制文件"), ("cp -r src/ dst/", "递归复制目录"), ("cp -a src/ dst/", "归档复制保留属性")], "高", "入门",
      "复制目录必须加 -r；目标同名会被静默覆盖，建议 -i 或 -n"),
    c("mv", "file", "移动或重命名", ["移动", "重命名", "mv"],
      [("mv a.txt b.txt", "重命名文件"), ("mv f.txt dir/", "移动到目录"), ("mv -i src dst", "覆盖前询问")], "高", "入门",
      "跨文件系统移动实为复制后删除，大文件较慢；目标同名会被静默覆盖，建议加 -i"),
    c("rm", "file", "删除文件或目录", ["删除", "移除", "rm"],
      [("rm file.txt", "删除文件"), ("rm -rf dir", "递归强制删除目录（危险）")], "高", "入门",
      "rm -rf / 或 rm -rf ~ 会销毁系统/家目录数据，务必先确认路径"),
    c("mkdir", "file", "创建目录", ["创建目录", "新建文件夹", "mkdir"],
      [("mkdir foo", "创建单级目录"), ("mkdir -p a/b/c", "递归创建多级目录")], "高", "入门",
      "父目录不存在时需 -p，否则失败"),
    c("rmdir", "file", "删除空目录", ["删除空目录", "rmdir"],
      [("rmdir empty/", "删除空目录")], "中", "入门", None, "rmdir 仅删空目录；rm -r 可删非空目录"),
    c("touch", "file", "创建空文件或更新时间戳", ["创建文件", "时间戳", "touch"],
      [("touch new.txt", "新建空文件"), ("touch -c old.txt", "仅更新时间不新建")], "高", "入门"),
    c("find", "file", "按条件查找文件", ["查找文件", "搜索", "find"],
      [("find . -name '*.py'", "按名查找"), ("find . -mtime -7", "查找 7 天内修改的文件")], "高", "日常",
      "路径放最前；-delete 误用会删文件，先不加该参数确认"),
    c("ln", "file", "创建链接", ["链接", "软链接", "硬链接", "ln"],
      [("ln -s target link", "创建软链接"), ("ln f hard", "创建硬链接")], "中", "日常",
      "软链接用 -s；源路径建议用绝对路径，否则移动后失效", None),
    c("readlink", "file", "查看链接指向", ["链接指向", "readlink"],
      [("readlink link", "打印链接目标")], "低", "日常"),
    c("realpath", "file", "解析为绝对路径", ["绝对路径", "realpath"],
      [("realpath f.txt", "输出规范绝对路径")], "低", "日常"),
    c("basename", "file", "取路径中的文件名", ["文件名", "basename"],
      [("basename /a/b/c.txt", "得到 c.txt")], "低", "日常"),
    c("dirname", "file", "取路径中的目录部分", ["目录名", "dirname"],
      [("dirname /a/b/c.txt", "得到 /a/b")], "低", "日常"),
    c("tree", "file", "树状显示目录结构", ["树状", "目录结构", "tree"],
      [("tree -L 2", "显示两层"), ("tree -a", "包含隐藏文件")], "中", "日常"),
    c("stat", "file", "显示文件详细状态", ["文件状态", "stat"],
      [("stat file.txt", "查看大小/权限/时间")], "中", "日常"),
    c("file", "file", "识别文件类型", ["文件类型", "file"],
      [("file a.bin", "识别为 ELF/文本等")], "中", "日常"),
    c("tee", "file", "输出到屏幕并写入文件", ["分流输出", "tee"],
      [("cmd | tee out.txt", "既显示又保存"), ("cmd | tee -a out.txt", "追加保存")], "中", "日常",
      "默认覆盖目标文件，追加需 -a"),
    c("pushd", "file", "压入目录栈并切换", ["目录栈", "pushd"],
      [("pushd dir", "切换并压栈")], "低", "日常"),
    c("popd", "file", "弹出目录栈", ["目录栈", "popd"],
      [("popd", "回到上一个目录")], "低", "日常"),

    c("eza", "file", "现代 ls 替代（彩色/图标/树状/Git 状态）", ["列表", "eza", "ls替代"],
      [("eza -la", "长格式含隐藏文件"), ("eza -T", "树状展示目录"), ("eza -a --git-ignore", "含隐藏但忽略 Git 忽略项")], "中", "日常",
      "需先安装；等价于增强版 ls，适合日常浏览"),
    c("fd", "file", "简单快速的 find 替代（默认递归/彩色/智能大小写）", ["查找", "fd", "find替代"],
      [("fd '*.py'", "按名查找"), ("fd -e rs src/", "按扩展名在 src 查找"), ("fd -i pattern", "忽略大小写")], "中", "日常",
      "默认递归且彩色输出；比 find 更直观，但需安装"),

    # ---- 文件查看 ----
    c("cat", "view", "查看/拼接文件内容", ["查看文件", "拼接", "cat"],
      [("cat f.txt", "打印全部内容"), ("cat a b > c", "拼接两文件")], "高", "入门",
      "大文件会刷屏，改用 less"),
    c("less", "view", "分页查看文件", ["分页查看", "less"],
      [("less f.txt", "上下翻页查看")], "高", "入门", None, "less 可上下翻；more 基本只能下翻"),
    c("more", "view", "逐屏查看文件", ["逐屏查看", "more"],
      [("more f.txt", "逐屏显示")], "中", "入门"),
    c("head", "view", "查看文件开头", ["开头", "head"],
      [("head -n 20 f", "看前 20 行"), ("head -c 100 f", "看前 100 字节")], "高", "入门",
      "默认显示前 10 行；head -n -5 表示「除末尾 5 行外全部」"),
    c("tail", "view", "查看文件末尾", ["末尾", "tail"],
      [("tail -n 20 f", "看后 20 行"), ("tail -f f", "实时跟踪新增内容")], "高", "入门",
      "跟踪日志首选 tail -f"),
    c("nl", "view", "带行号输出", ["行号", "nl"],
      [("nl f.txt", "输出带行号")], "低", "日常"),
    c("tac", "view", "逆序输出行", ["逆序", "tac"],
      [("tac f.txt", "从末尾到开头")], "低", "日常"),
    c("od", "view", "八进制/十六进制查看", ["二进制查看", "od"],
      [("od -c f", "以字符显示")], "低", "进阶"),
    c("xxd", "view", "十六进制转储", ["十六进制", "xxd"],
      [("xxd f.bin", "十六进制+ASCII")], "低", "进阶"),
    c("hexdump", "view", "十六进制转储", ["十六进制", "hexdump"],
      [("hexdump -C f", "规范十六进制格式")], "低", "进阶"),
    c("strings", "view", "提取可打印字符串", ["字符串", "strings"],
      [("strings a.out", "查看二进制中的字符串")], "低", "进阶"),
    c("fold", "view", "按宽度折行", ["折行", "fold"],
      [("fold -w 80 f", "每行 80 列")], "低", "日常"),
    c("pr", "view", "格式化分页输出", ["格式化", "pr"],
      [("pr f.txt", "加页眉分页")], "低", "日常"),

    c("bat", "view", "带语法高亮与行号的 cat 替代", ["查看", "高亮", "bat", "cat替代"],
      [("bat file.sh", "高亮显示文件"), ("bat -n file", "显示行号"), ("bat --paging=never file", "不分页一次输出")], "中", "日常",
      "需先安装；可作 man 分页器或配合 --style 控制显示"),

    # ---- 文本处理 ----
    c("grep", "text", "文本搜索", ["搜索文本", "匹配", "grep"],
      [("grep -rn 'TODO' src/", "递归搜索含 TODO 的文件"), ("grep -i error log", "忽略大小写")], "高", "入门",
      "正则默认识别基础语法；用 -E 启用扩展正则", None),
    c("egrep", "text", "扩展正则搜索（=grep -E）", ["扩展正则", "egrep"],
      [("egrep 'a|b' f", "匹配 a 或 b")], "中", "日常", None, "egrep 等价于 grep -E"),
    c("fgrep", "text", "固定字符串搜索（=grep -F）", ["固定字符串", "fgrep"],
      [("fgrep 'a$b' f", "按字面量匹配")], "低", "日常", None, "fgrep 不解释正则，等价于 grep -F"),
    c("sed", "text", "流编辑器", ["流编辑", "替换", "sed"],
      [("sed 's/foo/bar/g' f", "全局替换"), ("sed -i 's/a/b/g' f", "就地修改文件")], "高", "日常",
      "-i 直接改文件，先备份；macOS 需 -i ''"),
    c("awk", "text", "文本处理语言", ["字段处理", "awk"],
      [("awk '{print $1}' f", "打印第一列"), ("awk -F: '$3>100' /etc/passwd", "按 : 分割筛选")], "高", "进阶",
      "默认空格分隔；$0 整行、$1 第一列"),
    c("sort", "text", "排序", ["排序", "sort"],
      [("sort f.txt", "字典序排序"), ("sort -n -k2 f", "按第 2 列数值排序"), ("sort -u f", "排序并去重")], "高", "日常",
      "默认字典序；数值用 -n、反序 -r、按列 -k、去重 -u（常与 uniq 配合）"),
    c("uniq", "text", "去重（需先排序）", ["去重", "uniq"],
      [("sort f | uniq", "去重"), ("uniq -c", "统计出现次数")], "高", "日常",
      "uniq 只去相邻重复，通常先 sort"),
    c("cut", "text", "按列截取", ["截取列", "cut"],
      [("cut -d: -f1 /etc/passwd", "取第一字段"), ("cut -c1-10 f", "取 1-10 字符")], "高", "日常"),
    c("paste", "text", "横向合并文件", ["合并列", "paste"],
      [("paste a.txt b.txt", "并排合并")], "低", "日常"),
    c("join", "text", "按字段连接", ["连接", "join"],
      [("join a.txt b.txt", "按公共字段连接")], "低", "进阶"),
    c("comm", "text", "比较已排序文件", ["比较文件", "comm"],
      [("comm a.txt b.txt", "显示交集/差集")], "低", "日常"),
    c("diff", "text", "比较文件差异", ["比较差异", "diff"],
      [("diff a.txt b.txt", "逐行比较"), ("diff -u a b > p.patch", "生成补丁")], "高", "日常"),
    c("patch", "text", "应用补丁", ["打补丁", "patch"],
      [("patch < p.patch", "应用补丁")], "中", "日常",
      "打错可能损坏文件，先 --dry-run 预览"),
    c("tr", "text", "字符转换/删除", ["字符替换", "tr"],
      [("tr 'a-z' 'A-Z'", "转大写"), ("tr -d '\r'", "删除回车符")], "中", "日常"),
    c("wc", "text", "统计行/词/字节", ["统计", "wc"],
      [("wc -l f.txt", "统计行数"), ("wc -w f", "统计词数"), ("wc -c f", "统计字节数")], "高", "入门",
      "-l 行 / -w 词 / -c 字节 / -m 字符；不指定选项时依次给出三者"),
    c("split", "text", "拆分文件", ["拆分", "split"],
      [("split -l 1000 f", "每 1000 行拆分")], "低", "日常"),
    c("csplit", "text", "按上下文拆分", ["拆分", "csplit"],
      [("csplit f '/pattern/'", "按模式拆分")], "低", "进阶"),
    c("fmt", "text", "段落格式化", ["格式化", "fmt"],
      [("fmt -w 60 f", "每行 60 列")], "低", "日常"),
    c("expand", "text", "制表符转空格", ["制表符", "expand"],
      [("expand f.txt", "tab 转空格")], "低", "日常"),
    c("unexpand", "text", "空格转制表符", ["制表符", "unexpand"],
      [("unexpand -a f", "空格转 tab")], "低", "日常"),

    c("rg", "text", "极快的递归搜索（ripgrep，默认忽略 .gitignore）", ["搜索", "rg", "ripgrep", "grep替代"],
      [("rg 'TODO'", "递归搜索当前目录"), ("rg -i 'foo' src", "忽略大小写"), ("rg -n --hidden pat", "含隐藏文件搜索")], "中", "日常",
      "默认递归且跳过隐藏/忽略文件；-u 取消忽略、-F 按字面量匹配"),
    c("yq", "text", "命令行 YAML/XML/CSV/JSON 处理器（jq 的 YAML 版）", ["yaml", "yq", "处理"],
      [("yq '.service.port' f.yaml", "读取字段"), ("yq -i '.x=1' f.yaml", "原地修改"), ("yq -o=json f.yaml", "转 JSON 输出")], "中", "日常",
      "此处指 mikefarah/yq；与 Python 的 yq（jq 包装）不是同一工具"),

    # ---- 文件权限与属性 ----
    c("chmod", "perm", "修改权限", ["权限", "chmod"],
      [("chmod 644 f", "所有者读写他人只读"), ("chmod +x script.sh", "加可执行")], "高", "入门",
      "误用 777 会导致全网可写，存在安全风险"),
    c("chown", "perm", "修改属主", ["属主", "chown"],
      [("sudo chown u:g f", "改用户和组"), ("chown -R u dir", "递归修改")], "高", "日常",
      "改他人文件需 sudo；递归 -R 谨慎"),
    c("chgrp", "perm", "修改属组", ["属组", "chgrp"],
      [("chgrp dev f", "改组为 dev"), ("chgrp -R dev dir", "递归改组")], "中", "日常",
      "需是目标组成员或用 sudo；递归改组用 -R"),
    c("umask", "perm", "设置默认权限掩码", ["默认权限", "umask"],
      [("umask 022", "新建文件默认 755/644")], "中", "日常"),
    c("chattr", "perm", "修改文件扩展属性", ["扩展属性", "chattr"],
      [("chattr +i f", "不可修改/删除（immutable）"), ("chattr +a f", "仅可追加")], "低", "进阶",
      "需 root；+i 后连 root 也删不掉，用 -i 解除"),
    c("lsattr", "perm", "查看扩展属性", ["扩展属性", "lsattr"],
      [("lsattr f", "查看 chattr 属性")], "低", "进阶"),
    c("setfacl", "perm", "设置 ACL 细粒度权限", ["ACL", "setfacl"],
      [("setfacl -m u:alice:r f", "给用户 alice 读权限")], "低", "进阶"),
    c("getfacl", "perm", "查看 ACL", ["ACL", "getfacl"],
      [("getfacl f", "查看详细 ACL")], "低", "进阶"),

    # ---- 用户与用户组 ----
    c("sudo", "user", "以其他用户（默认 root）执行", ["提权", "sudo"],
      [("sudo apt update", "以 root 执行"), ("sudo -u www cmd", "以 www 执行")], "高", "入门",
      "滥用 sudo 有风险；用 sudo -l 查看可执行的命令"),
    c("su", "user", "切换用户", ["切换用户", "su"],
      [("su -", "切换到 root 并加载环境"), ("su alice", "切到 alice")], "高", "日常", None,
      "su - 加载目标用户环境；su 不加载"),
    c("useradd", "user", "新建用户", ["新建用户", "useradd"],
      [("sudo useradd -m alice", "建用户并建家目录")], "中", "日常",
      "不加 -m 可能不建家目录；用 useradd -m -s /bin/bash"),
    c("userdel", "user", "删除用户", ["删除用户", "userdel"],
      [("sudo userdel -r alice", "删用户并清家目录")], "低", "日常",
      "-r 才会删家目录，否则残留"),
    c("usermod", "user", "修改用户", ["修改用户", "usermod"],
      [("sudo usermod -aG sudo alice", "加入 sudo 组")], "中", "日常"),
    c("groupadd", "user", "新建组", ["新建组", "groupadd"],
      [("sudo groupadd dev", "建 dev 组")], "低", "日常"),
    c("groupdel", "user", "删除组", ["删除组", "groupdel"],
      [("sudo groupdel dev", "删 dev 组")], "低", "日常"),
    c("passwd", "user", "修改密码", ["密码", "passwd"],
      [("passwd", "改自己密码"), ("sudo passwd alice", "改他人密码")], "中", "日常"),
    c("chpasswd", "user", "批量改密码", ["批量密码", "chpasswd"],
      [("echo 'alice:new' | chpasswd", "批量设置")], "低", "进阶"),
    c("newgrp", "user", "切换有效组", ["切换组", "newgrp"],
      [("newgrp dev", "临时切换有效组")], "低", "日常"),
    c("gpasswd", "user", "管理组成员", ["组成员", "gpasswd"],
      [("sudo gpasswd -a alice dev", "加用户到组")], "低", "日常"),
    c("id", "user", "显示用户/组 ID", ["用户ID", "id"],
      [("id", "看当前 uid/gid"), ("id alice", "看指定用户")], "中", "入门"),
    c("whoami", "user", "显示当前用户名", ["当前用户", "whoami"],
      [("whoami", "打印当前用户名")], "中", "入门"),
    c("who", "user", "显示登录用户", ["登录用户", "who"],
      [("who", "看谁在线")], "低", "入门"),
    c("w", "user", "显示登录用户及进程", ["登录用户", "w"],
      [("w", "看用户与正在运行的命令")], "低", "日常"),
    c("last", "user", "最近登录记录", ["登录记录", "last"],
      [("last", "查看登录历史")], "低", "日常"),
    c("lastlog", "user", "所有用户最后登录", ["最后登录", "lastlog"],
      [("lastlog", "各用户末次登录")], "低", "日常"),
    c("groups", "user", "显示用户所属组", ["所属组", "groups"],
      [("groups alice", "看 alice 的组")], "低", "入门"),
    c("visudo", "user", "安全编辑 sudoers", ["sudoers", "visudo"],
      [("sudo visudo", "编辑 sudo 配置（带语法检查）")], "低", "进阶",
      "务必用 visudo 而非直接改，避免锁死 sudo"),
    c("finger", "user", "用户信息查询", ["用户信息", "finger"],
      [("finger alice", "查看用户详情")], "低", "日常"),

    c("adduser", "user", "交互式创建用户（Debian 系封装 useradd）", ["新增用户", "adduser"],
      [("sudo adduser alice", "交互式创建并建家目录"), ("sudo adduser --disabled-login bob", "创建禁登录账户")], "中", "日常",
      "Red Hat 系常无此命令，改用 useradd -m；比 useradd 更友好"),

    # ---- 进程管理 ----
    c("ps", "proc", "查看进程", ["进程", "ps"],
      [("ps aux", "看全部进程"), ("ps -ef | grep nginx", "查 nginx"), ("ps -u root", "看指定用户进程")], "高", "入门",
      "aux 为 BSD 风格、-ef 为 UNIX 风格；配合 grep 过滤、--sort 排序"),
    c("top", "proc", "实时进程监控", ["实时监控", "top"],
      [("top", "动态查看资源占用")], "高", "日常", None, "top 实时；htop 更友好（需安装）"),
    c("htop", "proc", "增强版进程监控", ["进程监控", "htop"],
      [("htop", "彩色可交互监控")], "中", "日常"),
    c("kill", "proc", "发送信号终止进程", ["结束进程", "kill"],
      [("kill 1234", "默认 SIGTERM"), ("kill -9 1234", "强制 SIGKILL")], "高", "日常",
      "先 SIGTERM(-15)，不行再 -9；-9 可能丢数据"),
    c("pkill", "proc", "按名结束进程", ["按名结束", "pkill"],
      [("pkill nginx", "结束所有 nginx")], "中", "日常",
      "误杀同名进程，先 pkill -l 预览"),
    c("killall", "proc", "按名结束全部", ["按名结束", "killall"],
      [("killall python", "结束所有 python")], "中", "日常"),
    c("pgrep", "proc", "按名查找 PID", ["查找PID", "pgrep"],
      [("pgrep nginx", "找 nginx 的 PID")], "中", "日常"),
    c("pidof", "proc", "查进程 PID", ["PID", "pidof"],
      [("pidof nginx", "返回 nginx PID")], "低", "日常"),
    c("jobs", "proc", "查看后台任务", ["后台任务", "jobs"],
      [("jobs", "列出当前 shell 的后台任务")], "中", "日常"),
    c("bg", "proc", "任务转后台", ["后台", "bg"],
      [("bg %1", "把任务 1 放后台")], "中", "日常"),
    c("fg", "proc", "任务转前台", ["前台", "fg"],
      [("fg %1", "把任务 1 调回前台")], "中", "日常"),
    c("nohup", "proc", "退出后继续运行", ["后台运行", "nohup"],
      [("nohup cmd &", "断开终端仍运行")], "中", "日常"),
    c("disown", "proc", "脱离 shell 作业", ["脱离作业", "disown"],
      [("disown", "移除作业防 HUP 信号")], "低", "进阶"),
    c("nice", "proc", "调整优先级启动", ["优先级", "nice"],
      [("nice -n 10 cmd", "低优先级运行")], "低", "进阶"),
    c("renice", "proc", "调整运行中优先级", ["优先级", "renice"],
      [("renice -n 5 -p 1234", "改 PID 优先级")], "低", "进阶"),
    c("at", "proc", "定时一次性任务", ["定时任务", "at"],
      [("echo 'cmd' | at 18:00", "18 点执行")], "低", "日常"),
    c("batch", "proc", "系统空闲时执行", ["空闲执行", "batch"],
      [("batch", "负载低时运行")], "低", "日常"),
    c("crontab", "proc", "周期性任务", ["定时任务", "crontab"],
      [("crontab -e", "编辑计划任务"), ("crontab -l", "列出任务")], "中", "日常",
      "格式 分 时 日 月 周；注意环境变量可能缺失"),
    c("runlevel", "proc", "查看运行级别", ["运行级别", "runlevel"],
      [("runlevel", "显示当前/上一级别")], "低", "日常"),
    c("init", "proc", "切换运行级别", ["运行级别", "init"],
      [("sudo init 0", "关机（旧式）")], "低", "日常"),
    c("watch", "proc", "周期执行并刷新", ["周期执行", "watch"],
      [("watch -n 1 'ls -l'", "每秒刷新")], "中", "日常"),
    c("lsof", "proc", "列出打开的文件/端口", ["打开文件", "端口", "lsof"],
      [("lsof -i :80", "看 80 端口占用"), ("lsof /var/log", "谁在写该文件")], "中", "进阶"),
    c("strace", "proc", "跟踪系统调用", ["系统调用", "strace"],
      [("strace -p 1234", "跟踪进程系统调用")], "低", "进阶"),
    c("time", "proc", "统计命令耗时", ["耗时", "time"],
      [("time ./build.sh", "测运行时间")], "中", "日常"),
    c("timeout", "proc", "限时运行命令", ["超时", "timeout"],
      [("timeout 10 cmd", "10 秒后终止")], "低", "日常"),

    # ---- 磁盘与文件系统 ----
    c("df", "disk", "查看磁盘空间", ["磁盘空间", "df"],
      [("df -h", "人类可读显示各分区"), ("df -i", "查看 inode 使用"), ("df -T", "显示文件系统类型")], "高", "入门",
      "空间满但文件不多时，可能是 inode 耗尽，用 df -i 排查"),
    c("du", "disk", "查看目录/文件大小", ["目录大小", "du"],
      [("du -sh *", "当前各子项总大小"), ("du -h --max-depth=1", "一层深度")], "高", "入门",
      "du 统计文件实际占用；df 看分区整体"),
    c("mount", "disk", "挂载文件系统", ["挂载", "mount"],
      [("sudo mount /dev/sdb1 /mnt", "挂载到 /mnt"), ("sudo mount -a", "挂载 fstab 中全部")], "中", "日常", None, "mount 挂载；umount 卸载；可加 -o ro 只读、loop 挂镜像"),
    c("umount", "disk", "卸载文件系统", ["卸载", "umount"],
      [("sudo umount /mnt", "卸载")], "中", "日常",
      "设备忙时无法卸载，先关闭占用进程"),
    c("fdisk", "disk", "磁盘分区工具", ["分区", "fdisk"],
      [("sudo fdisk /dev/sdb", "交互式分区")], "低", "进阶",
      "操作分区有数据丢失风险"),
    c("parted", "disk", "分区工具（支持 GPT）", ["分区", "parted"],
      [("sudo parted /dev/sdb", "分区（支持大盘）")], "低", "进阶"),
    c("lsblk", "disk", "列出块设备", ["块设备", "lsblk"],
      [("lsblk", "树状显示磁盘与分区")], "中", "日常"),
    c("blkid", "disk", "查看设备 UUID/类型", ["设备UUID", "blkid"],
      [("sudo blkid", "显示设备 UUID/文件系统")], "低", "日常"),
    c("mkfs", "disk", "格式化文件系统", ["格式化", "mkfs"],
      [("sudo mkfs.ext4 /dev/sdb1", "格式化为 ext4")], "低", "进阶",
      "格式化会清空数据！"),
    c("dd", "disk", "按块复制（磁盘镜像）", ["块复制", "dd"],
      [("dd if=in of=out bs=4M", "克隆/备份"), ("dd if=/dev/zero of=disk.img", "造镜像"), ("dd if=in of=out bs=4M status=progress", "显示进度")], "低", "进阶",
      "if=/dev/sda 写错 of= 会毁盘，务必核对；bs 越大越快但更占内存"),
    c("fsck", "disk", "检查修复文件系统", ["文件系统检查", "fsck"],
      [("sudo fsck /dev/sdb1", "检查并修复")], "低", "进阶",
      "需在卸载状态下运行"),
    c("e2fsck", "disk", "ext 文件系统检查", ["ext检查", "e2fsck"],
      [("sudo e2fsck -f /dev/sdb1", "强制检查")], "低", "进阶"),
    c("tune2fs", "disk", "调整 ext 文件系统参数", ["ext参数", "tune2fs"],
      [("sudo tune2fs -l /dev/sdb1", "查看参数")], "低", "进阶"),
    c("badblocks", "disk", "检测坏块", ["坏块", "badblocks"],
      [("sudo badblocks -v /dev/sdb", "扫描坏块")], "低", "进阶"),
    c("nvme", "disk", "NVMe 固态管理", ["nvme", "nvme"],
      [("sudo nvme list", "列出 nvme 设备")], "低", "进阶"),
    c("losetup", "disk", "管理回环设备", ["回环设备", "losetup"],
      [("sudo losetup -f disk.img", "挂载镜像为设备")], "低", "进阶"),
    c("sync", "disk", "刷新缓存到磁盘", ["同步", "sync"],
      [("sync", "强制写入磁盘（卸载前用）")], "低", "日常"),
    c("mkswap", "disk", "创建交换分区", ["交换分区", "mkswap"],
      [("sudo mkswap /dev/sdb2", "建 swap")], "低", "进阶"),
    c("swapon", "disk", "启用交换", ["启用swap", "swapon"],
      [("sudo swapon /dev/sdb2", "启用 swap")], "低", "进阶"),
    c("swapoff", "disk", "关闭交换", ["关闭swap", "swapoff"],
      [("sudo swapoff /dev/sdb2", "关闭")], "低", "进阶"),
    c("dumpe2fs", "disk", "导出 ext 超级块信息", ["ext信息", "dumpe2fs"],
      [("sudo dumpe2fs /dev/sdb1", "看超级块")], "低", "进阶"),

    c("ncdu", "disk", "基于 ncurses 的磁盘用量分析器（交互式找大目录）", ["磁盘分析", "ncdu", "大文件"],
      [("ncdu /", "扫描根目录用量"), ("ncdu -x /", "不跨文件系统")], "中", "日常",
      "需先安装；方向键浏览，d 删除、q 退出"),
    c("duf", "disk", "人性化的 df 替代（列出挂载点与用量）", ["磁盘", "duf", "df替代"],
      [("duf", "列出所有挂载点")], "低", "日常", "需先安装"),
    c("dust", "disk", "树状展示目录大小的 du 替代", ["目录大小", "dust", "du替代"],
      [("dust", "当前目录大小树"), ("dust -d 2", "显示两层")], "低", "日常", "需先安装"),
    c("quota", "disk", "查看用户/组的磁盘配额", ["配额", "quota"],
      [("quota -s", "人类可读显示当前用户配额"), ("quota -v user", "查看指定用户")], "低", "日常",
      "需文件系统启用配额并在挂载时配置（usrquota/grpquota）"),

    # ---- 网络 ----
    c("ping", "net", "测试网络连通", ["连通测试", "ping"],
      [("ping -c 4 example.com", "发 4 个包")], "高", "入门"),
    c("curl", "net", "传输 URL 数据", ["下载", "HTTP", "curl"],
      [("curl -O url", "下载并保留远程文件名"), ("curl -L -o f url", "跟随重定向下载"), ("curl -I url", "只看响应头")], "高", "日常",
      "管道执行下载脚本前先确认来源可信；-L 跟随重定向、-sS 静默但显示错误"),
    c("wget", "net", "下载文件", ["下载", "wget"],
      [("wget url", "下载到当前目录"), ("wget -c url", "断点续传"), ("wget -P /tmp url", "指定保存目录")], "高", "日常",
      "-O 指定文件名、-P 指定目录、-r 整站镜像（谨慎使用）"),
    c("ssh", "net", "远程安全登录", ["远程登录", "ssh"],
      [("ssh user@host", "登录远程"), ("ssh -p 2222 user@host", "指定端口"), ("ssh -i key.pem user@host", "指定密钥")], "高", "日常",
      "首次连接会确认主机指纹；推荐密钥登录并禁用密码（sshd_config）"),
    c("scp", "net", "安全复制文件", ["远程复制", "scp"],
      [("scp f.txt user@host:/tmp", "上传"), ("scp -r dir user@host:~/", "递归上传")], "高", "日常"),
    c("sftp", "net", "交互式安全传输", ["安全传输", "sftp"],
      [("sftp user@host", "交互传文件")], "中", "日常"),
    c("rsync", "net", "增量同步", ["增量同步", "rsync"],
      [("rsync -avz src/ host:/dst", "远程增量备份"), ("rsync -a --delete src/ dst/", "镜像同步")], "高", "进阶",
      "--delete 会删目标多余文件，先 --dry-run"),
    c("netstat", "net", "网络状态（旧）", ["网络状态", "netstat"],
      [("netstat -tunlp", "看监听端口")], "中", "日常", None, "netstat 已过时，推荐 ss"),
    c("ss", "net", "查看套接字（新）", ["套接字", "ss"],
      [("ss -tunlp", "看监听端口（替代 netstat）")], "中", "日常", None, "ss 比 netstat 更快更全"),
    c("ip", "net", "网络配置（新）", ["网络配置", "ip"],
      [("ip addr", "看网卡 IP"), ("ip route", "看路由表")], "中", "日常", None, "ip 取代 ifconfig/route"),
    c("ifconfig", "net", "网络接口配置（旧）", ["网卡配置", "ifconfig"],
      [("ifconfig", "看接口信息")], "中", "入门", None, "已被 ip 命令取代"),
    c("traceroute", "net", "路由追踪", ["路由追踪", "traceroute"],
      [("traceroute example.com", "显示路径跳数")], "中", "日常"),
    c("mtr", "net", "路由实时诊断", ["路由诊断", "mtr"],
      [("mtr example.com", "持续监控路径")], "低", "日常"),
    c("dig", "net", "DNS 查询", ["DNS查询", "dig"],
      [("dig example.com", "查 A 记录"), ("dig @8.8.8.8 example.com", "指定 DNS")], "中", "进阶"),
    c("host", "net", "简易 DNS 查询", ["DNS查询", "host"],
      [("host example.com", "解析域名")], "低", "日常", None, "host 简单；dig 更详细"),
    c("whois", "net", "域名/IP 注册信息", ["whois", "whois"],
      [("whois example.com", "查注册信息")], "低", "日常"),
    c("nc", "net", "网络瑞士军刀", ["网络工具", "nc"],
      [("nc -l 1234", "监听端口"), ("nc host 1234 < f", "传文件")], "低", "进阶"),
    c("nmap", "net", "端口扫描", ["端口扫描", "nmap"],
      [("nmap -sV host", "扫描服务版本")], "低", "进阶",
      "扫描他人系统可能违法，仅用于自有资产"),
    c("tcpdump", "net", "抓包分析", ["抓包", "tcpdump"],
      [("sudo tcpdump -i eth0 port 80", "抓 80 端口")], "低", "进阶"),
    c("iptables", "net", "防火墙规则", ["防火墙", "iptables"],
      [("sudo iptables -L", "列出规则"), ("sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT", "放行 22")], "低", "进阶",
      "规则重启会丢失，需 iptables-save 持久化；改动可能断连，谨慎；新系统多用 nftables/ufw"),
    c("ufw", "net", "简易防火墙", ["防火墙", "ufw"],
      [("sudo ufw enable", "启用"), ("sudo ufw allow 22", "放行 22")], "低", "日常", None, "ufw 是 iptables 的友好封装"),
    c("arp", "net", "查看 ARP 表", ["ARP", "arp"],
      [("arp -n", "看 IP-MAC 映射")], "低", "日常"),
    c("socat", "net", "多协议中继", ["中继", "socat"],
      [("socat TCP-LISTEN:1234,fork TCP:host:80", "端口转发")], "低", "进阶"),
    c("nslookup", "net", "DNS 查询（旧）", ["DNS查询", "nslookup"],
      [("nslookup example.com", "查解析")], "低", "入门", None, "已被 dig/host 取代"),

    c("iwconfig", "net", "配置无线网卡接口（已逐步被 iw 取代）", ["无线", "iwconfig", "wifi"],
      [("iwconfig wlan0", "查看无线接口状态"), ("iwconfig wlan0 essid MYWIFI", "连接热点")], "低", "日常",
      "老旧工具；新系统推荐 iw，部分发行版已不含 iwconfig"),
    c("iw", "net", "现代无线设备配置工具（取代 iwconfig）", ["无线", "iw", "wifi"],
      [("iw dev", "列出无线设备"), ("iw dev wlan0 link", "查看连接信息"), ("iw wlan0 scan", "扫描附近热点")], "低", "进阶"),
    c("sshfs", "net", "通过 SSH 把远程目录挂载到本地（FUSE）", ["挂载", "sshfs", "远程目录"],
      [("sshfs user@host:/path /mnt", "挂载远程目录"), ("fusermount -u /mnt", "卸载")], "中", "日常",
      "基于 FUSE，需安装 sshfs；卸载用 fusermount -u（非 umount）"),
    c("http", "net", "HTTPie：人性化的命令行 HTTP 客户端（curl 友好替代）", ["http", "httpie", "请求"],
      [("http GET example.com", "发送 GET"), ("http POST example.com name=Joe", "发送 POST 表单"), ("http -a user:pw GET url", "带基本认证")], "中", "日常",
      "需先安装 httpie；注意与 Python 的 http 模块无关"),
    c("iftop", "net", "实时显示网络带宽按连接的占用", ["带宽", "iftop", "流量"],
      [("sudo iftop -i eth0", "监控网卡流量")], "低", "日常", "需 root 且安装；按 h 看帮助、q 退出"),
    c("nethogs", "net", "按进程显示实时网络流量占用", ["进程流量", "nethogs"],
      [("sudo nethogs", "按进程查看流量")], "低", "日常", "需 root 且安装"),

    # ---- 压缩与归档 ----
    c("tar", "archive", "打包/解包", ["打包", "tar"],
      [("tar -czf a.tar.gz dir/", "gzip 打包"), ("tar -cjf a.tar.bz2 dir/", "bzip2 打包"), ("tar -xzf a.tar.gz -C /tmp", "解压到 /tmp")], "高", "入门",
      "z=gzip/j=bzip2/J=xz；顺序敏感：f 后紧跟文件名；解压前先 tar -tzf 看内容"),
    c("gzip", "archive", "gzip 压缩", ["压缩", "gzip"],
      [("gzip f.txt", "压缩为 f.txt.gz（删原文件）"), ("gzip -k f.txt", "保留原文件")], "高", "日常",
      "默认删除源文件，保留用 -k 或 gzip -c > "),
    c("gunzip", "archive", "解压 gzip", ["解压", "gunzip"],
      [("gunzip f.gz", "解压")], "低", "日常", None, "gunzip 即 gzip -d"),
    c("bzip2", "archive", "bzip2 压缩", ["压缩", "bzip2"],
      [("bzip2 f.txt", "更高压缩率更慢")], "低", "日常"),
    c("xz", "archive", "xz 压缩", ["压缩", "xz"],
      [("xz -9 f.txt", "极高压缩率")], "低", "日常"),
    c("zip", "archive", "打包为 zip", ["zip", "zip"],
      [("zip -r a.zip dir/", "递归打包")], "中", "日常"),
    c("unzip", "archive", "解压 zip", ["解压zip", "unzip"],
      [("unzip a.zip -d out/", "解压到 out")], "中", "日常"),
    c("7z", "archive", "7-Zip 压缩", ["7z", "7z"],
      [("7z a a.7z dir/", "压缩"), ("7z x a.7z", "解压")], "低", "日常"),
    c("zstd", "archive", "Zstandard 压缩", ["zstd", "zstd"],
      [("zstd f.txt", "快速高压缩")], "低", "日常"),
    c("lz4", "archive", "lz4 快速压缩", ["lz4", "lz4"],
      [("lz4 f.txt", "极快压缩")], "低", "日常"),
    c("compress", "archive", "老式压缩", ["压缩", "compress"],
      [("compress f", "生成 .f.Z")], "低", "日常"),
    c("unrar", "archive", "解压 rar", ["解压rar", "unrar"],
      [("unrar x a.rar", "解压 rar")], "低", "日常"),
    c("rar", "archive", "创建 rar", ["rar", "rar"],
      [("rar a a.rar dir/", "打包为 rar（需安装）")], "低", "日常"),
    c("zcat", "archive", "查看 gzip 内容", ["查看压缩", "zcat"],
      [("zcat f.gz", "不解压直接看")], "低", "日常", None, "zcat 即 gzip -dc"),

    c("brotli", "archive", "Brotli 压缩（Web 常用，压缩比高）", ["压缩", "brotli"],
      [("brotli -q 11 -o f.br f", "最高压缩"), ("brotli -d f.br", "解压")], "低", "日常"),
    c("pigz", "archive", "并行 gzip，利用多核加速压缩", ["并行压缩", "pigz", "gzip"],
      [("tar -cf - dir | pigz > d.tgz", "并行压缩 tar 流"), ("pigz -d d.tgz", "解压")], "低", "日常",
      "接口与 gzip 兼容；多文件/大文件时比 gzip 快很多"),
    c("pax", "archive", "POSIX 标准归档工具（可处理 cpio/tar 格式）", ["归档", "pax"],
      [("pax -w -f a.pax dir/", "打包目录"), ("pax -r -f a.pax", "解包")], "低", "日常",
      "可跨 cpio/tar 格式互换；-r 读、-w 写、-f 指定文件"),

    # ---- 系统信息与监控 ----
    c("uname", "sys", "系统内核信息", ["内核信息", "uname"],
      [("uname -a", "全部系统信息")], "中", "入门"),
    c("uptime", "sys", "运行时长与负载", ["运行时长", "uptime"],
      [("uptime", "看运行时间与负载")], "中", "入门"),
    c("free", "sys", "内存使用", ["内存", "free"],
      [("free -h", "人类可读内存"), ("free -h -s 2", "每 2 秒刷新")], "高", "入门",
      "关注 available 列（真正可用内存）；buff/cache 可被回收"),
    c("lscpu", "sys", "CPU 信息", ["CPU信息", "lscpu"],
      [("lscpu", "看 CPU 架构/核数")], "中", "日常"),
    c("lsmem", "sys", "内存拓扑", ["内存", "lsmem"],
      [("lsmem", "看内存块布局")], "低", "日常"),
    c("lsusb", "sys", "USB 设备列表", ["USB", "lsusb"],
      [("lsusb", "列出 USB 设备")], "低", "日常"),
    c("lspci", "sys", "PCI 设备列表", ["PCI", "lspci"],
      [("lspci", "列出 PCI 设备")], "低", "日常"),
    c("lshw", "sys", "硬件详情", ["硬件", "lshw"],
      [("sudo lshw", "完整硬件信息")], "低", "进阶"),
    c("dmidecode", "sys", "DMI/BIOS 信息", ["硬件", "dmidecode"],
      [("sudo dmidecode -t memory", "内存信息")], "低", "进阶"),
    c("dmesg", "sys", "内核环形缓冲", ["内核日志", "dmesg"],
      [("dmesg | tail", "看最近内核消息"), ("sudo dmesg -w", "实时")], "中", "进阶"),
    c("journalctl", "sys", "systemd 日志", ["系统日志", "journalctl"],
      [("journalctl -xe", "看错误日志"), ("journalctl -u nginx", "某服务日志")], "中", "日常"),
    c("hostnamectl", "sys", "主机名管理", ["主机名", "hostnamectl"],
      [("hostnamectl", "查看/设置主机名")], "低", "日常"),
    c("timedatectl", "sys", "时间日期管理", ["时间", "timedatectl"],
      [("timedatectl", "看时钟与 NTP")], "低", "日常"),
    c("localectl", "sys", "本地化设置", ["本地化", "localectl"],
      [("localectl", "看语言/键盘设置")], "低", "日常"),
    c("loginctl", "sys", "登录会话管理", ["会话", "loginctl"],
      [("loginctl", "查看登录会话")], "低", "日常"),
    c("iostat", "sys", "CPU/IO 统计", ["IO统计", "iostat"],
      [("iostat -x 1", "每秒扩展 IO 统计")], "低", "进阶"),
    c("vmstat", "sys", "虚拟内存统计", ["内存统计", "vmstat"],
      [("vmstat 1", "每秒系统统计")], "低", "进阶"),
    c("sar", "sys", "系统活动报告", ["系统报告", "sar"],
      [("sar -u 1 3", "CPU 使用率采样")], "低", "进阶"),
    c("mpstat", "sys", "CPU 核心统计", ["CPU统计", "mpstat"],
      [("mpstat -P ALL 1", "每核使用率")], "低", "进阶"),
    c("nproc", "sys", "CPU 核心数", ["核心数", "nproc"],
      [("nproc", "输出逻辑核心数")], "低", "入门"),
    c("sensors", "sys", "温度监控", ["温度", "sensors"],
      [("sensors", "看 CPU/主板温度")], "低", "日常"),

    c("lsb_release", "sys", "显示发行版信息（如 Ubuntu 22.04）", ["发行版", "lsb_release"],
      [("lsb_release -a", "显示全部信息"), ("lsb_release -cs", "显示代号（如 jammy）")], "中", "日常",
      "部分精简系统需安装 lsb-release 包"),
    c("neofetch", "sys", "美观展示系统信息与 ASCII logo", ["系统信息", "neofetch"],
      [("neofetch", "显示系统概览")], "低", "日常", "需先安装；fastfetch 为更快的替代品"),
    c("btop", "sys", "现代化资源监控（CPU/内存/网络/磁盘，彩色 UI）", ["监控", "btop", "资源"],
      [("btop", "启动监控界面")], "低", "日常", "需先安装；htop 的增强版"),
    c("glances", "sys", "跨平台系统监控，含传感器与告警阈值", ["监控", "glances"],
      [("glances", "启动监控"), ("glances -w", "开启 Web 模式")], "低", "日常", "需先安装；可配合 -s 作服务端"),

    # ---- 关机与系统控制 ----
    c("shutdown", "power", "关机/重启", ["关机", "shutdown"],
      [("sudo shutdown -h now", "立即关机"), ("sudo shutdown -r 20:00", "20 点重启")], "中", "入门",
      "远程机器慎用，确认不会断错"),
    c("reboot", "power", "重启", ["重启", "reboot"],
      [("sudo reboot", "立即重启")], "中", "入门"),
    c("poweroff", "power", "关机", ["关机", "poweroff"],
      [("sudo poweroff", "立即关机")], "中", "入门"),
    c("halt", "power", "停止系统", ["停机", "halt"],
      [("sudo halt", "停止 CPU（需断电）")], "低", "入门"),
    c("systemctl", "power", "systemd 服务管理", ["服务管理", "systemctl"],
      [("sudo systemctl restart nginx", "重启服务"), ("systemctl status nginx", "看状态"), ("systemctl enable nginx", "开机自启")], "高", "日常",
      "enable 才开机自启；改配置后 daemon-reload"),
    c("telinit", "power", "切换运行级别（旧）", ["运行级别", "telinit"],
      [("sudo telinit 3", "切到多用户")], "低", "日常", None, "现代多用 systemctl 的 target"),

    # ---- 软件包管理 ----
    c("apt", "pkg", "Debian 系包管理（新）", ["包管理", "apt"],
      [("sudo apt update", "更新索引"), ("sudo apt install -y nginx", "安装"), ("sudo apt remove nginx", "卸载")], "高", "入门"),
    c("apt-get", "pkg", "底层 apt（脚本用）", ["包管理", "apt-get"],
      [("sudo apt-get update", "更新索引")], "中", "入门", None, "交互/脚本推荐 apt；apt-get 兼容旧脚本"),
    c("dpkg", "pkg", "Debian 底层包操作", ["包管理", "dpkg"],
      [("sudo dpkg -i pkg.deb", "装本地 deb"), ("dpkg -l", "列出已装包")], "中", "日常", None, "dpkg 不解决依赖；apt 会"),
    c("yum", "pkg", "RHEL 旧包管理", ["包管理", "yum"],
      [("sudo yum install nginx", "安装")], "低", "日常"),
    c("dnf", "pkg", "RHEL 新包管理", ["包管理", "dnf"],
      [("sudo dnf install nginx", "安装")], "低", "日常", None, "dnf 取代 yum"),
    c("rpm", "pkg", "RHEL 底层包管理", ["包管理", "rpm"],
      [("rpm -qa", "列出已装包"), ("sudo rpm -ivh pkg.rpm", "装 rpm")], "低", "日常"),
    c("pacman", "pkg", "Arch 包管理", ["包管理", "pacman"],
      [("sudo pacman -Syu", "更新系统"), ("sudo pacman -S pkg", "安装")], "低", "日常"),
    c("zypper", "pkg", "openSUSE 包管理", ["包管理", "zypper"],
      [("sudo zypper install pkg", "安装")], "低", "日常"),
    c("apk", "pkg", "Alpine 包管理", ["包管理", "apk"],
      [("apk add pkg", "安装（容器常用）")], "低", "日常"),
    c("snap", "pkg", "通用快照包", ["snap", "snap"],
      [("sudo snap install code", "安装")], "低", "日常"),
    c("flatpak", "pkg", "沙盒应用", ["flatpak", "flatpak"],
      [("flatpak install app", "安装")], "低", "日常"),
    c("brew", "pkg", "macOS/Homebrew", ["brew", "brew"],
      [("brew install wget", "macOS 装包")], "低", "日常"),
    c("apt-cache", "pkg", "查询包信息", ["包查询", "apt-cache"],
      [("apt-cache search nginx", "搜索包")], "低", "日常"),

    c("aptitude", "pkg", "Debian/Ubuntu 高级包管理（依赖求解 + TUI）", ["aptitude", "包管理"],
      [("sudo aptitude install pkg", "安装包"), ("sudo aptitude search kw", "搜索"), ("sudo aptitude safe-upgrade", "安全升级")], "低", "日常",
      "需安装；能更好地处理依赖冲突，优于 apt-get"),
    c("emerge", "pkg", "Gentoo 的源码包管理器", ["emerge", "gentoo", "包管理"],
      [("sudo emerge --ask pkg", "安装包"), ("sudo emerge --sync", "同步 Portage 树"), ("sudo emerge -uDN @world", "更新整个系统")], "低", "进阶",
      "编译安装耗时；--ask 先预览、--oneshot 不写入 world"),

    # ---- 内核模块 ----
    c("lsmod", "kernel", "列出已加载模块", ["内核模块", "lsmod"],
      [("lsmod", "看已加载模块")], "低", "日常"),
    c("modprobe", "kernel", "加载/卸载模块", ["模块加载", "modprobe"],
      [("sudo modprobe kvm", "加载模块"), ("sudo modprobe -r kvm", "卸载")], "低", "进阶",
      "修改需谨慎，错误模块可致系统不稳"),
    c("insmod", "kernel", "插入模块文件", ["模块插入", "insmod"],
      [("sudo insmod drv.ko", "加载指定 .ko")], "低", "进阶", None, "insmod 不自动解决依赖；modprobe 会"),
    c("rmmod", "kernel", "移除模块", ["模块移除", "rmmod"],
      [("sudo rmmod drv", "移除模块")], "低", "进阶"),
    c("depmod", "kernel", "生成模块依赖", ["模块依赖", "depmod"],
      [("sudo depmod", "更新依赖映射")], "低", "进阶"),
    c("modinfo", "kernel", "查看模块信息", ["模块信息", "modinfo"],
      [("modinfo kvm", "看模块详情/参数")], "低", "日常"),

    # ---- Shell 内建命令 ----
    c("echo", "shell", "输出文本", ["输出", "echo"],
      [("echo hello", "打印文本"), ("echo $PATH", "打印变量")], "高", "入门"),
    c("printf", "shell", "格式化输出", ["格式化输出", "printf"],
      [("printf '%s\n' a b", "格式输出")], "中", "日常", None, "printf 更可控；echo 简单"),
    c("export", "shell", "导出环境变量", ["环境变量", "export"],
      [("export PATH=$PATH:/opt/bin", "追加 PATH")], "高", "日常"),
    c("alias", "shell", "设置命令别名", ["别名", "alias"],
      [("alias ll='ls -la'", "设别名")], "中", "日常"),
    c("unalias", "shell", "取消别名", ["取消别名", "unalias"],
      [("unalias ll", "删除别名")], "低", "日常"),
    c("source", "shell", "当前 shell 执行脚本", ["执行脚本", "source"],
      [("source ~/.bashrc", "重载配置")], "高", "日常", None, "source 在当前 shell 执行；./script 在子 shell"),
    c("history", "shell", "命令历史", ["历史", "history"],
      [("history", "列出历史"), ("!123", "执行第 123 条")], "中", "入门"),
    c("read", "shell", "读取输入", ["读取输入", "read"],
      [("read name", "读入变量")], "低", "进阶"),
    c("eval", "shell", "执行字符串命令", ["执行字符串", "eval"],
      [("eval \"$cmd\"", "动态执行")], "低", "进阶",
      "拼接用户输入执行有注入风险"),
    c("exec", "shell", "替换当前进程", ["替换进程", "exec"],
      [("exec bash", "替换当前 shell")], "低", "进阶"),
    c("trap", "shell", "捕获信号", ["信号捕获", "trap"],
      [("trap 'clean' EXIT", "退出时清理")], "低", "进阶"),
    c("set", "shell", "设置 shell 选项", ["shell选项", "set"],
      [("set -e", "遇错即停"), ("set -x", "打印执行命令")], "低", "进阶"),
    c("unset", "shell", "删除变量/函数", ["删除变量", "unset"],
      [("unset VAR", "删除变量")], "低", "日常"),
    c("shopt", "shell", "shell 行为选项", ["shell选项", "shopt"],
      [("shopt -s globstar", "启用 ** 递归匹配")], "低", "进阶"),
    c("type", "shell", "显示命令类型", ["命令类型", "type"],
      [("type ls", "显示是别名/内建/文件")], "中", "日常"),
    c("command", "shell", "绕过别名执行", ["绕过别名", "command"],
      [("command ls", "忽略 ls 别名")], "低", "日常"),
    c("builtin", "shell", "调用内建", ["内建", "builtin"],
      [("builtin cd", "强制用内建 cd")], "低", "进阶"),
    c("let", "shell", "算术运算", ["算术", "let"],
      [("let x=x+1", "整数运算")], "低", "进阶"),
    c("wait", "shell", "等待后台作业", ["等待", "wait"],
      [("wait %1", "等任务完成")], "低", "进阶"),
    c("ulimit", "shell", "资源限制", ["资源限制", "ulimit"],
      [("ulimit -n 65535", "提高打开文件数上限")], "低", "进阶"),
    c("test", "shell", "条件测试", ["条件测试", "test"],
      [("test -f f.txt", "判断文件存在")], "低", "进阶", None, "test 即 [ ... ]"),
    c("fc", "shell", "编辑/重放历史", ["历史", "fc"],
      [("fc", "编辑上条命令")], "低", "进阶"),
    c("[", "shell", "条件测试内建", ["条件测试", "["],
      [("[ -d dir ]", "判断目录存在")], "低", "进阶", None, "[ 是 test 的同名内建，注意收尾 ]"),

    c("fzf", "shell", "通用模糊查找器，可与任意命令管道配合", ["模糊查找", "fzf"],
      [("fzf", "交互式查找文件"), ("history | fzf", "在历史中查找"), ("vim $(fzf)", "选文件用 vim 打开")], "中", "日常",
      "需先安装；常配合 **<Tab> 补全与 Ctrl-T 插入文件路径"),

    # ---- 编辑器与工具 ----
    c("nano", "editor", "简易编辑器", ["编辑器", "nano"],
      [("nano f.txt", "新手友好编辑")], "中", "入门"),
    c("emacs", "editor", "Emacs 编辑器", ["编辑器", "emacs"],
      [("emacs f.txt", "打开")], "低", "日常"),
    c("ed", "editor", "行编辑器", ["行编辑器", "ed"],
      [("ed f.txt", "行编辑")], "低", "进阶"),
    c("man", "editor", "查看手册", ["手册", "man"],
      [("man ls", "看 ls 手册"), ("man -k keyword", "按关键词搜手册")], "高", "入门"),
    c("info", "editor", "GNU 信息文档", ["文档", "info"],
      [("info coreutils", "看 GNU 文档")], "低", "日常"),
    c("which", "editor", "显示命令路径", ["命令路径", "which"],
      [("which python", "看 python 位置")], "高", "入门"),
    c("whereis", "editor", "定位命令/源码/手册", ["定位", "whereis"],
      [("whereis ls", "找 ls 相关文件")], "低", "日常"),
    c("whatis", "editor", "一行命令描述", ["描述", "whatis"],
      [("whatis ls", "看简介")], "低", "入门"),
    c("locate", "editor", "快速文件搜索（数据库）", ["文件搜索", "locate"],
      [("locate nginx.conf", "从数据库搜")], "中", "日常",
      "依赖 updatedb；新文件可能搜不到"),
    c("updatedb", "editor", "更新搜索数据库", ["更新数据库", "updatedb"],
      [("sudo updatedb", "重建 locate 索引")], "低", "日常"),
    c("date", "editor", "显示/设置日期", ["日期", "date"],
      [("date", "当前时间"), ("date +%Y%m%d", "格式化")], "中", "入门"),
    c("cal", "editor", "显示日历", ["日历", "cal"],
      [("cal", "当月日历"), ("cal 2026", "全年")], "低", "入门"),
    c("sleep", "editor", "暂停指定秒数", ["暂停", "sleep"],
      [("sleep 5", "等 5 秒")], "中", "日常"),
    c("yes", "editor", "持续输出", ["持续输出", "yes"],
      [("yes | cmd", "自动确认")], "低", "日常"),
    c("clear", "editor", "清屏", ["清屏", "clear"],
      [("clear", "清屏")], "中", "入门"),
    c("script", "editor", "记录终端会话", ["记录会话", "script"],
      [("script session.log", "记录全部输出")], "低", "日常"),
    c("wall", "editor", "向所有终端发消息", ["广播", "wall"],
      [("wall '维护通知'", "群发消息")], "低", "日常"),
    c("mesg", "editor", "控制消息接收", ["消息", "mesg"],
      [("mesg n", "拒收 wall 消息")], "低", "日常"),

    c("tldr", "editor", "简化版 man，给出命令的常见示例", ["tldr", "示例", "帮助"],
      [("tldr tar", "查看 tar 常用示例"), ("tldr -p linux grep", "指定平台")], "中", "日常",
      "需先安装；覆盖命令的最常用场景，比 man 更直给"),
    c("cheat", "editor", "查看社区维护的命令速查表", ["cheat", "速查"],
      [("cheat ssh", "查看 ssh 速查"), ("cheat -l", "列出可用速查表")], "低", "日常", "需先安装"),
    c("reset", "editor", "重置终端状态（乱码/卡死后恢复）", ["终端重置", "reset"],
      [("reset", "恢复终端到默认状态")], "中", "日常",
      "比 clear 更彻底；终端显示异常（如二进制文件刷屏）时可用"),

    # ---- Vim 编辑器（启动/退出、模式、移动、编辑、复制粘贴、文本对象、搜索替换、可视、缓冲、窗口、标签、折叠、宏、标记、补全、配置、外部命令） ----
    c("vim", "vim", "启动 Vim 并打开文件", ["启动", "打开文件", "编辑器", "vim"],
      [("vim file.txt", "打开文件"), ("vim +42 file.txt", "打开并跳到第 42 行")], "高", "入门",
      ":q! 强制退出不保存会丢失改动；只读可用 vim -R", "vim 是 vi 的增强版；nano 更简单但功能弱"),
    c("vim -d", "vim", "以差异比对模式打开（vimdiff）", ["差异", "比对", "vimdiff", "vim -d"],
      [("vim -d a.txt b.txt", "并排对比两个文件")], "中", "日常"),
    c("vim -R", "vim", "只读模式打开文件", ["只读", "view", "vim -R"],
      [("vim -R file.txt", "只读防误写")], "中", "日常"),
    c("view", "vim", "只读模式查看文件（等同 vim -R）", ["只读", "view"],
      [("view file.txt", "只读查看")], "低", "日常"),
    c("vim -r", "vim", "恢复交换文件", ["恢复", "交换文件", "vim -r"],
      [("vim -r .file.txt.swp", "崩溃后恢复未保存内容")], "低", "进阶"),
    c("i", "vim", "进入插入模式（光标前）", ["插入", "输入", "i"],
      [("i", "在光标前开始输入")], "高", "入门"),
    c("a", "vim", "进入插入模式（光标后）", ["插入后", "a"],
      [("a", "在光标后开始输入")], "高", "入门"),
    c("I", "vim", "在行首（首个非空白）插入", ["行首插入", "I"],
      [("I", "跳到行首非空白处插入")], "高", "入门"),
    c("A", "vim", "在行尾插入", ["行尾插入", "A"],
      [("A", "跳到行尾插入")], "高", "入门"),
    c("o", "vim", "在下方新建一行并插入", ["新行", "下方", "o"],
      [("o", "下方开新行输入")], "高", "入门"),
    c("O", "vim", "在上方新建一行并插入", ["新行", "上方", "O"],
      [("O", "上方开新行输入")], "高", "入门"),
    c("s", "vim", "删除光标字符并插入", ["替换字符", "s"],
      [("s", "删字符并插入")], "中", "日常"),
    c("S", "vim", "删除整行并插入", ["替换行", "S"],
      [("S", "删整行并插入")], "中", "日常", None, "S 等同 cc（修改整行）"),
    c("cc", "vim", "修改整行（删除并插入）", ["修改行", "cc"],
      [("cc", "清空当前行并插入")], "中", "日常", None, "cc 等同 S；与 dd 区别：cc 保留行、进入插入"),
    c("R", "vim", "进入替换模式（逐字符覆盖）", ["替换模式", "R"],
      [("R", "覆盖输入而非插入")], "中", "日常", None, "R 与 r 区别：R 持续替换，r 只换一个字符"),
    c("Esc", "vim", "返回普通模式", ["退出插入", "普通模式", "Esc"],
      [("Esc", "从任意模式回到普通模式"), ("Ctrl+[", "Esc 的等价键")], "高", "入门",
      "插入模式下忘了按 Esc 会直接把字母写进文件"),
    c("v", "vim", "进入字符可视化模式", ["选择", "可视化", "v"],
      [("v", "逐字符选择")], "高", "日常"),
    c("V", "vim", "进入行可视化模式", ["行选择", "V"],
      [("V", "整行选择")], "高", "日常"),
    c("Ctrl+v", "vim", "进入块（列）可视化模式", ["列选择", "块选择", "Ctrl+v"],
      [("Ctrl+v", "按列选择矩形区域")], "中", "进阶",
      "Windows 下 Ctrl+v 可能被剪贴板占用，可用 Ctrl+q 代替"),
    c("h", "vim", "光标左移", ["左移", "h"],
      [("h", "←")], "高", "入门"),
    c("j", "vim", "光标下移", ["下移", "j"],
      [("j", "↓")], "高", "入门"),
    c("k", "vim", "光标上移", ["上移", "k"],
      [("k", "↑")], "高", "入门"),
    c("l", "vim", "光标右移", ["右移", "l"],
      [("l", "→")], "高", "入门"),
    c("w（移动）", "vim", "跳到下一个词首", ["词首", "移动", "w"],
      [("w", "下一词开头")], "高", "入门", None, "w 按标点分词；W 按空格分 WORD"),
    c("W", "vim", "跳到下一个 WORD 首（空白分隔）", ["WORD", "W"],
      [("W", "跳过标点，按空格跳")], "中", "日常"),
    c("b", "vim", "跳到上一个词首", ["上一词", "b"],
      [("b", "回退一词")], "高", "入门"),
    c("e", "vim", "跳到词尾", ["词尾", "e"],
      [("e", "到词末尾")], "中", "日常"),
    c("0", "vim", "跳到行首", ["行首", "0"],
      [("0", "绝对行首")], "高", "入门", None, "0 到行首；^ 到首个非空白字符"),
    c("^", "vim", "跳到行首首个非空白字符", ["软行首", "^"],
      [("^", "跳过行首缩进")], "高", "入门"),
    c("$", "vim", "跳到行尾", ["行尾", "$"],
      [("$", "到行末")], "高", "入门"),
    c("g_", "vim", "跳到行尾最后一个非空白字符", ["行尾非空白", "g_"],
      [("g_", "到最末非空字符")], "低", "进阶"),
    c("gg", "vim", "跳到文件首行", ["文件首", "gg"],
      [("gg", "到第一行")], "高", "入门"),
    c("G", "vim", "跳到文件尾行", ["文件尾", "G"],
      [("G", "到最后一行")], "高", "入门"),
    c(":n", "vim", "跳到第 n 行", ["跳行", "行号", ":n"],
      [(":42", "跳到第 42 行"), ("42G", "等价写法")], "高", "入门"),
    c("H", "vim", "光标移到屏幕顶部", ["屏幕顶", "H"],
      [("H", "到屏幕第一行")], "中", "日常"),
    c("M", "vim", "光标移到屏幕中部", ["屏幕中", "M"],
      [("M", "到屏幕中间行")], "低", "日常"),
    c("L", "vim", "光标移到屏幕底部", ["屏幕底", "L"],
      [("L", "到屏幕最后行")], "中", "日常"),
    c("%", "vim", "在匹配的括号/引号间跳转", ["匹配括号", "%"],
      [("%", "在 () [] {} 间跳转")], "中", "日常"),
    c("{", "vim", "跳到上一段落", ["上一段", "{"],
      [("{", "到前一段开头")], "中", "日常"),
    c("}", "vim", "跳到下一段落", ["下一段", "}"],
      [("}", "到后一段开头")], "中", "日常"),
    c("(", "vim", "跳到上一句", ["上一句", "("],
      [("(", "到前一句")], "低", "日常"),
    c(")", "vim", "跳到下一句", ["下一句", ")"],
      [(")", "到后一句")], "低", "日常"),
    c("Ctrl+f", "vim", "向下翻一页", ["下页", "Ctrl+f"],
      [("Ctrl+f", "整页下翻")], "中", "日常"),
    c("Ctrl+b", "vim", "向上翻一页", ["上页", "Ctrl+b"],
      [("Ctrl+b", "整页上翻")], "中", "日常"),
    c("Ctrl+d", "vim", "向下翻半页", ["下半页", "Ctrl+d"],
      [("Ctrl+d", "半页下翻")], "中", "日常"),
    c("Ctrl+u", "vim", "向上翻半页", ["上半页", "Ctrl+u"],
      [("Ctrl+u", "半页上翻")], "中", "日常"),
    c("zz", "vim", "把当前行滚到屏幕中央", ["居中", "zz"],
      [("zz", "当前行居中")], "中", "日常"),
    c("fx", "vim", "在当前行查找字符 x（向后）", ["查找字符", "fx"],
      [("fa", "跳到本行下一个 a")], "中", "日常"),
    c("Fx", "vim", "在当前行查找字符 x（向前）", ["向前查找字符", "Fx"],
      [("Fa", "跳到本行上一个 a")], "低", "日常"),
    c("tx", "vim", "跳到字符 x 之前（向后）", ["前移字符", "tx"],
      [("ta", "停在 a 前")], "低", "日常"),
    c(";", "vim", "重复上次字符查找", ["重复查找", ";"],
      [(";", "同向再找一次")], "低", "日常"),
    c("*", "vim", "搜索光标下的单词（向下）", ["搜索单词", "*"],
      [("*", "查找当前词")], "中", "日常"),
    c("#", "vim", "搜索光标下的单词（向上）", ["向上搜索单词", "#"],
      [("#", "向上找当前词")], "中", "日常"),
    c("Ctrl+o", "vim", "在跳转历史中后退", ["跳转后退", "Ctrl+o"],
      [("Ctrl+o", "回到上次光标位置")], "中", "进阶"),
    c("Ctrl+i", "vim", "在跳转历史中前进", ["跳转前进", "Ctrl+i"],
      [("Ctrl+i", "前进到下一处光标位置")], "中", "进阶"),
    c("``", "vim", "跳回上次光标位置", ["上次位置", "``"],
      [("``", "回到上一次停留处")], "低", "进阶"),
    c("x", "vim", "删除光标下字符", ["删除字符", "x"],
      [("x", "删一个字符")], "高", "入门"),
    c("X", "vim", "删除光标前字符", ["删除前字符", "X"],
      [("X", "删光标左边字符")], "中", "入门"),
    c("dw", "vim", "删除一个词", ["删除词", "dw"],
      [("dw", "删到词尾")], "高", "日常"),
    c("dd（删行）", "vim", "删除（剪切）整行", ["删除行", "删行", "dd"],
      [("dd", "删一行（可 p 粘贴）"), ("3dd", "删 3 行")], "高", "入门",
      "dd 实际是剪切，删后可用 p 粘贴；误删用 u 撤销"),
    c("D", "vim", "删除从光标到行尾", ["删除到行尾", "D"],
      [("D", "清空光标到行末")], "高", "日常", None, "D 等同 d$；d0 删到行首"),
    c("cw", "vim", "修改一个词（删除并插入）", ["修改词", "cw"],
      [("cw", "改一个词")], "中", "日常"),
    c("C", "vim", "修改从光标到行尾", ["修改到行尾", "C"],
      [("C", "改光标到行末")], "中", "日常"),
    c("r", "vim", "替换单个字符", ["替换字符", "r"],
      [("rx", "把光标字符换成 x")], "中", "日常", None, "r 只换一个字符；R 进入持续替换模式"),
    c("J", "vim", "把下一行合并到当前行", ["合并行", "J"],
      [("J", "两行合成一行")], "中", "日常"),
    c("~", "vim", "切换光标字符大小写", ["大小写", "~"],
      [("~", "反转大小写")], "低", "日常"),
    c("gu", "vim", "将文本转为小写", ["转小写", "gu"],
      [("guw", "当前词转小写")], "低", "进阶"),
    c("gU", "vim", "将文本转为大写", ["转大写", "gU"],
      [("gUw", "当前词转大写")], "低", "进阶"),
    c(".", "vim", "重复上一次修改", ["重复", "."],
      [(".", "再执行一次上次编辑")], "高", "日常",
      "配合动作使用最强，如 dw. 连续删词"),
    c("u", "vim", "撤销", ["撤销", "u"],
      [("u", "撤销一步")], "高", "入门"),
    c("Ctrl+r", "vim", "重做（反撤销）", ["重做", "Ctrl+r"],
      [("Ctrl+r", "恢复被撤销的改动")], "高", "入门"),
    c("U", "vim", "撤销当前行的全部改动", ["撤销整行", "U"],
      [("U", "还原本行到最初")], "低", "日常"),
    c("yy", "vim", "复制（yank）整行", ["复制行", "yy"],
      [("yy", "复制一行"), ("3yy", "复制 3 行")], "高", "入门",
      "Y 在部分配置等同 yy；y 是复制操作符"),
    c("yw", "vim", "复制一个词", ["复制词", "yw"],
      [("yw", "复制光标所在词")], "中", "日常"),
    c("y$", "vim", "复制到行尾", ["复制到行尾", "y$"],
      [("y$", "复制光标到行末")], "中", "日常"),
    c("p", "vim", "粘贴到光标后/下方", ["粘贴", "p"],
      [("p", "在光标后/下一行粘贴")], "高", "入门"),
    c("P", "vim", "粘贴到光标前/上方", ["粘贴前", "P"],
      [("P", "在光标前/上一行粘贴")], "高", "入门"),
    c("diw", "vim", "删除光标所在词（不含空格）", ["删词", "diw"],
      [("diw", "删除 inner word")], "中", "进阶",
      "文本对象：d/c/y + i/a + 对象；i 不含边界，a 含边界"),
    c("ciw", "vim", "修改光标所在词", ["改词", "ciw"],
      [("ciw", "清空当前词并输入")], "中", "进阶"),
    c("di\"", "vim", "删除引号内的文本", ["删引号内", "di\""],
      [("di\"", "删除 \"...\" 内容")], "中", "进阶"),
    c("ci\"", "vim", "修改引号内的文本", ["改引号内", "ci\""],
      [("ci\"", "改 \"...\" 内容")], "中", "进阶"),
    c("di(", "vim", "删除括号内的文本", ["删括号内", "di("],
      [("di(", "删除 (...) 内容")], "中", "进阶"),
    c("dit", "vim", "删除标签内的文本", ["删标签内", "dit"],
      [("dit", "删除 <tag>...</tag> 内容")], "低", "进阶"),
    c("/pattern", "vim", "向下搜索模式（支持正则）", ["搜索", "查找", "/pattern"],
      [("/foo", "向下找 foo"), ("/the\\<", "正则匹配词首")], "高", "入门",
      "n 下一个，N 上一个；:noh 取消高亮"),
    c("?pattern", "vim", "向上搜索模式", ["向上搜索", "?pattern"],
      [("?foo", "向上找 foo")], "中", "入门"),
    c("n", "vim", "跳到下一个搜索匹配", ["下一个匹配", "n"],
      [("n", "同向下一处")], "高", "入门"),
    c("N", "vim", "跳到上一个搜索匹配", ["上一个匹配", "N"],
      [("N", "反向上一处")], "高", "入门"),
    c(":%s", "vim", "全局查找替换", ["替换", "查找替换", ":%s"],
      [(":%s/foo/bar/g", "全文把 foo 换成 bar"), (":%s/foo/bar/gc", "每处确认")], "高", "日常",
      "漏写 g 只换每行首个；c 逐个确认更安全"),
    c(":s", "vim", "当前行查找替换", ["行内替换", ":s"],
      [(":s/old/new/g", "本行替换")], "中", "日常"),
    c(":5,20s", "vim", "在指定行范围替换", ["区间替换", ":5,20s"],
      [(":5,20s/old/new/g", "第 5–20 行替换")], "中", "日常"),
    c(":set ic", "vim", "搜索忽略大小写", ["忽略大小写", ":set ic"],
      [(":set ic", "搜索不区分大小写")], "中", "日常"),
    c(":set hls", "vim", "高亮搜索结果", ["高亮搜索", ":set hls"],
      [(":set hls", "开启搜索高亮"), (":noh", "临时关闭高亮")], "中", "日常"),
    c(":w", "vim", "保存文件", ["保存", "写盘", ":w"],
      [(":w", "保存"), (":w new.txt", "另存为")], "高", "入门"),
    c(":q", "vim", "退出", ["退出", ":q"],
      [(":q", "退出（有改动会报错）")], "高", "入门"),
    c(":q!", "vim", "强制退出不保存", ["强制退出", ":q!"],
      [(":q!", "丢弃改动退出")], "高", "入门",
      "会丢失所有未保存改动，慎用"),
    c(":wq", "vim", "保存并退出", ["保存退出", ":wq"],
      [(":wq", "保存后退出")], "高", "入门", None, ":wq / :x / ZZ 都保存退出；:x 仅在改动时写盘"),
    c(":x", "vim", "保存并退出（仅改动时写盘）", ["保存退出", ":x"],
      [(":x", "等同 ZZ")], "中", "入门", None, ":x 比 :wq 更优：未改动不更新 mtime"),
    c("ZZ", "vim", "普通模式下保存并退出", ["保存退出", "ZZ"],
      [("ZZ", "按两次 Z 退出")], "中", "入门"),
    c(":e", "vim", "打开/切换到另一个文件", ["打开文件", ":e"],
      [(":e other.txt", "切换到另一文件")], "中", "日常"),
    c(":e!", "vim", "从磁盘重新加载当前文件", ["重新加载", ":e!"],
      [(":e!", "放弃改动重读磁盘")], "中", "日常"),
    c(":qa", "vim", "退出所有缓冲区", ["退出全部", ":qa"],
      [(":qa", "关闭所有"), (":qa!", "强制关闭全部")], "中", "日常"),
    c(":ls", "vim", "列出缓冲区", ["缓冲区列表", ":ls"],
      [(":ls", "查看已打开文件")], "中", "日常"),
    c(":bn", "vim", "切换到下一个缓冲区", ["下一缓冲区", ":bn"],
      [(":bn", "下一个文件")], "中", "日常"),
    c(":bp", "vim", "切换到上一个缓冲区", ["上一缓冲区", ":bp"],
      [(":bp", "上一个文件")], "中", "日常"),
    c(":bd", "vim", "关闭当前缓冲区", ["关闭缓冲区", ":bd"],
      [(":bd", "关掉当前文件")], "中", "日常"),
    c(":sp", "vim", "横向分屏", ["水平分屏", ":sp"],
      [(":sp", "上下分屏同文件"), (":sp new.txt", "分屏打开新文件")], "中", "日常"),
    c(":vsp", "vim", "纵向分屏", ["垂直分屏", ":vsp"],
      [(":vsp", "左右分屏")], "中", "日常"),
    c("Ctrl+w", "vim", "窗口切换/调整（前缀键）", ["窗口切换", "Ctrl+w"],
      [("Ctrl+w h/j/k/l", "四向切换窗口"), ("Ctrl+w =", "等分窗口"), ("Ctrl+w +", "增高")], "中", "进阶",
      "所有窗口操作都以 Ctrl+w 开头；误按会触发切换"),
    c(":tabnew", "vim", "新建标签页", ["新标签", ":tabnew"],
      [(":tabnew", "开新标签")], "低", "进阶"),
    c("gt", "vim", "切换到下一个标签页", ["下一标签", "gt"],
      [("gt", "下一标签")], "低", "进阶"),
    c("gT", "vim", "切换到上一个标签页", ["上一标签", "gT"],
      [("gT", "上一标签")], "低", "进阶"),
    c("za", "vim", "切换折叠展开/收起", ["折叠", "za"],
      [("za", "开/关当前折叠")], "低", "进阶"),
    c("zo", "vim", "打开折叠", ["展开折叠", "zo"],
      [("zo", "展开一层")], "低", "进阶"),
    c("zc", "vim", "关闭折叠", ["收起折叠", "zc"],
      [("zc", "收起一层")], "低", "进阶"),
    c("zR", "vim", "展开全部折叠", ["全部展开", "zR"],
      [("zR", "递归展开")], "低", "进阶"),
    c("zM", "vim", "收起全部折叠", ["全部收起", "zM"],
      [("zM", "递归收起")], "低", "进阶"),
    c("qa", "vim", "录制宏到寄存器 a", ["录制宏", "qa"],
      [("qa ... q", "录动作到 a"), ("@a", "回放 a"), ("20@a", "回放 20 次")], "中", "进阶",
      "录制以 q 开始、以 q 结束；注意 q 也是退出键"),
    c("@a", "vim", "回放寄存器 a 中的宏", ["回放宏", "@a"],
      [("@a", "执行宏 a"), ("@@", "重复上次宏")], "中", "进阶"),
    c("ma", "vim", "设置标记 a", ["设置标记", "ma"],
      [("ma", "在当前位置记 a"), ("`a", "跳回标记 a")], "低", "进阶"),
    c("Ctrl+n", "vim", "插入模式单词补全（下一个）", ["补全", "Ctrl+n"],
      [("Ctrl+n", "向下补全单词")], "中", "日常"),
    c("Ctrl+p", "vim", "插入模式单词补全（上一个）", ["补全", "Ctrl+p"],
      [("Ctrl+p", "向上补全单词")], "中", "日常"),
    c(":set nu", "vim", "显示行号", ["行号", ":set nu"],
      [(":set nu", "显示行号"), (":set nonu", "隐藏行号")], "高", "入门"),
    c(":set rnu", "vim", "显示相对行号", ["相对行号", ":set rnu"],
      [(":set rnu", "配合 5j/3k 跳转更方便")], "中", "日常"),
    c(":syntax on", "vim", "开启语法高亮", ["语法高亮", ":syntax on"],
      [(":syntax on", "彩色显示代码")], "中", "入门"),
    c(":set ai", "vim", "开启自动缩进", ["自动缩进", ":set ai"],
      [(":set ai", "新行沿用缩进")], "中", "日常"),
    c(":set list", "vim", "显示不可见字符（tab/行尾）", ["不可见字符", ":set list"],
      [(":set list", "显示制表符与行尾符")], "中", "日常"),
    c(":set wrap", "vim", "开启长行自动换行显示", ["换行显示", ":set wrap"],
      [(":set wrap", "长行折行"), (":set nowrap", "不折行")], "中", "日常"),
    c(":retab", "vim", "按当前设置转换 tab 与空格", ["转换制表符", ":retab"],
      [(":retab", "统一缩进风格")], "低", "进阶"),
    c(":r", "vim", "读入文件内容到当前缓冲", ["读入文件", ":r"],
      [(":r other.txt", "把文件内容插入光标下")], "中", "日常"),
    c(":!cmd", "vim", "在 Vim 内执行外部 shell 命令", ["执行命令", ":!cmd"],
      [(":!ls", "查看目录"), (":r !date", "插入命令输出")], "中", "日常"),
    c(":%!", "vim", "用外部命令过滤全部内容", ["外部过滤", ":%!"],
      [(":%!sort", "全文排序"), (":%!grep foo", "只保留含 foo 的行")], "低", "进阶"),
    c(":help", "vim", "打开内置帮助", ["帮助", ":help"],
      [(":help :w", "查某命令帮助")], "中", "入门"),
    c("vimtutor", "vim", "启动交互式 Vim 教程", ["教程", "vimtutor"],
      [("vimtutor", "终端输入学习基础")], "中", "入门"),

    # ===== 新增补充：文件与目录操作 =====
    c("mktemp", "file", "安全创建临时文件或目录", ["临时文件", "临时目录", "mktemp"],
      [("mktemp", "创建随机名临时文件"), ("mktemp -d", "创建临时目录")], "低", "日常"),
    c("shred", "file", "安全擦除文件（不可恢复）", ["安全删除", "擦除", "shred"],
      [("shred -u file", "覆盖后删除文件"), ("shred -n 3 -z file", "覆写3次再填零")], "低", "进阶",
      "默认仅覆盖不删除，需 -u 才真正删除；SSD/日志类存储仍可能残留"),
    c("install", "file", "复制文件并设置权限/属主", ["安装文件", "install"],
      [("install -m 755 a.sh /usr/local/bin/", "复制并设可执行权限"), ("install -d dir", "创建目录")], "低", "日常"),
    c("rename", "file", "按规则批量重命名文件", ["批量重命名", "rename"],
      [("rename 's/.txt/.md/' *.txt", "扩展名批量改"), ("rename 'y/A-Z/a-z/' *", "文件名转小写")], "低", "日常",
      "多为 Perl 版 rename，语法是表达式；使用前确认本地版本"),

    # ===== 新增补充：文件查看 =====
    c("view", "view", "以只读模式打开文件（Vim 只读）", ["只读查看", "view"],
      [("view file.txt", "只读打开，禁止修改保存")], "低", "入门",
      None, "view 等价于 vim -R，改后无法 :w 保存"),

    # ===== 新增补充：文本处理 =====
    c("md5sum", "text", "计算/校验 MD5 摘要", ["md5", "校验和", "md5sum"],
      [("md5sum file.iso", "计算摘要"), ("md5sum -c file.iso.md5", "校验文件完整性")], "中", "日常"),
    c("sha256sum", "text", "计算/校验 SHA-256 摘要", ["sha256", "校验和", "sha256sum"],
      [("sha256sum file.iso", "计算 SHA-256"), ("sha256sum -c file.iso.sha256", "校验")], "中", "日常"),
    c("sha1sum", "text", "计算/校验 SHA-1 摘要", ["sha1", "校验和", "sha1sum"],
      [("sha1sum file", "计算 SHA-1")], "低", "日常"),
    c("iconv", "text", "字符编码转换", ["编码转换", "iconv"],
      [("iconv -f gbk -t utf-8 in.txt -o out.txt", "GBK 转 UTF-8")], "中", "日常"),
    c("jq", "text", "解析与处理 JSON 数据", ["json", "json处理", "jq"],
      [("cat data.json | jq '.name'", "提取字段"), ("jq '.[] | .id' list.json", "遍历取 id")], "中", "日常",
      "jq 表达式用单引号包裹，避免被 shell 展开"),
    c("rev", "text", "反转每行字符顺序", ["反转", "rev"],
      [("rev file.txt", "逐行逆序输出")], "低", "日常"),
    c("column", "text", "将文本按列对齐格式化", ["列对齐", "column"],
      [("column -t file.txt", "按空白对齐成表"), ("ls | column", "多列显示")], "低", "日常"),
    c("shuf", "text", "随机打乱文本行", ["随机", "shuffle", "shuf"],
      [("shuf -n 3 file.txt", "随机取3行"), ("shuf file.txt", "全量洗牌")], "低", "日常"),
    c("numfmt", "text", "人类可读数字与原始数互转", ["数字格式化", "numfmt"],
      [("numfmt --to=iec 1048576", "转为 1.0M"), ("echo 1K | numfmt --from=iec", "转为 1024")], "低", "日常"),
    c("colrm", "text", "删除每行指定列范围", ["删除列", "colrm"],
      [("colrm 10 20 < file", "删第10-20列")], "低", "日常"),
    c("look", "text", "列出字典中以前缀开头的行", ["前缀查找", "look"],
      [("look foo", "找以 foo 开头的词")], "低", "日常"),
    c("tsort", "text", "按依赖关系拓扑排序", ["拓扑排序", "tsort"],
      [("tsort deps.txt", "按依赖排序")], "低", "进阶"),

    # ===== 新增补充：文件权限与属性 =====
    c("chcon", "perm", "修改 SELinux 安全上下文", ["selinux", "上下文", "chcon"],
      [("chcon -t httpd_sys_content_t /srv/www", "改文件上下文")], "低", "进阶",
      "重启或 restorecon 可能还原上下文，需配合 semanage 持久化"),
    c("restorecon", "perm", "按策略恢复 SELinux 上下文", ["selinux", "restorecon"],
      [("restorecon -Rv /srv/www", "递归恢复目录上下文")], "低", "进阶"),
    c("getenforce", "perm", "查看 SELinux 当前模式", ["selinux", "模式", "getenforce"],
      [("getenforce", "显示 Enforcing/Permissive")], "低", "日常"),
    c("setenforce", "perm", "临时切换 SELinux 模式", ["selinux", "setenforce"],
      [("setenforce 0", "临时置 Permissive"), ("setenforce 1", "置 Enforcing")], "低", "日常",
      "仅临时生效，重启后恢复；永久需改 /etc/selinux/config"),
    c("setfattr", "perm", "设置文件扩展属性(xattr)", ["扩展属性", "xattr", "setfattr"],
      [("setfattr -n user.remark -v 'test' file", "写入扩展属性")], "低", "进阶"),
    c("getfattr", "perm", "查看文件扩展属性(xattr)", ["扩展属性", "xattr", "getfattr"],
      [("getfattr -d file", "显示全部扩展属性"), ("getfattr -n user.remark file", "查看指定属性")], "低", "进阶"),

    # ===== 新增补充：用户与用户组 =====
    c("groupmod", "user", "修改用户组属性", ["修改组", "groupmod"],
      [("groupmod -n newname oldname", "重命名组")], "低", "日常"),
    c("chage", "user", "设置/查看密码有效期", ["密码过期", "chage"],
      [("chage -l alice", "查看过期信息"), ("chage -M 90 alice", "密码最长90天")], "低", "日常"),
    c("chsh", "user", "修改用户登录 Shell", ["修改shell", "chsh"],
      [("chsh -s /bin/bash alice", "改登录 Shell")], "低", "日常"),
    c("chfn", "user", "修改用户 finger 信息", ["finger信息", "chfn"],
      [("chfn -f 'Alice Li' alice", "改真实姓名")], "低", "日常"),
    c("getent", "user", "查询系统管理数据库(passwd/group/hosts 等)", ["查询数据库", "getent"],
      [("getent passwd alice", "查用户信息"), ("getent hosts example.com", "解析主机")], "中", "日常",
      None, "getent 综合本地文件与 NSS(如 LDAP)，比直接读 /etc/passwd 更准"),
    c("logname", "user", "显示当前登录用户名", ["登录名", "logname"],
      [("logname", "打印登录账号")], "低", "日常"),
    c("faillog", "user", "查看登录失败记录", ["失败登录", "faillog"],
      [("faillog -u alice", "查看某用户失败记录"), ("faillog -a", "全部用户")], "低", "日常"),
    c("nologin", "user", "设为不可交互登录的 shell", ["禁止登录", "nologin"],
      [("usermod -s /usr/sbin/nologin alice", "禁止该用户交互登录")], "低", "日常"),
    c("vipw", "user", "安全编辑 /etc/passwd", ["编辑passwd", "vipw"],
      [("vipw", "锁定并编辑口令文件")], "低", "进阶",
      None, "vipw 编辑时加锁避免并发损坏；对应组文件用 vigr"),
    c("pwck", "user", "校验 /etc/passwd 一致性", ["校验passwd", "pwck"],
      [("pwck", "检查账号文件完整性")], "低", "日常"),

    # ===== 新增补充：进程管理 =====
    c("pstree", "proc", "以树状显示进程关系", ["进程树", "pstree"],
      [("pstree", "树状列出进程"), ("pstree -p", "附带 PID")], "中", "日常",
      None, "pstree 直观展示父子关系；ps 更偏表格字段"),
    c("fuser", "proc", "识别占用文件/端口的进程", ["占用进程", "fuser"],
      [("fuser -k /mnt", "杀掉占用该目录的进程"), ("fuser -n tcp 80", "查占用 80 端口的进程")], "中", "日常",
      "fuser -k 会直接发 SIGKILL，慎用"),
    c("ionice", "proc", "设置进程 I/O 调度优先级", ["io优先级", "ionice"],
      [("ionice -c 3 -p 1234", "设为空闲级"), ("ionice -c 2 -n 0 tar cf x.tar /data", "高优执行")], "低", "进阶"),
    c("taskset", "proc", "绑定进程到指定 CPU", ["cpu亲和性", "taskset"],
      [("taskset -c 0,1 ./app", "限定用 CPU0/1"), ("taskset -p 0x3 1234", "查看/设置掩码")], "低", "进阶"),
    c("pmap", "proc", "显示进程内存映射", ["内存映射", "pmap"],
      [("pmap 1234", "查看进程内存分布"), ("pmap -x 1234", "含详细扩展信息")], "低", "日常"),
    c("service", "proc", "SysV 风格服务管理", ["服务管理", "service"],
      [("service nginx restart", "重启服务"), ("service ssh status", "查状态")], "中", "日常",
      None, "systemd 系统下 service 多为兼容封装，建议优先用 systemctl"),
    c("tmux", "proc", "终端复用器(会话持久化)", ["终端复用", "会话", "tmux"],
      [("tmux new -s work", "新建会话"), ("tmux attach -t work", "重连会话"), ("tmux ls", "列出会话")], "中", "日常",
      "脱离会话用 Ctrl+b d；关闭终端不会杀死 tmux 内进程"),
    c("screen", "proc", "终端复用器(会话持久化)", ["终端复用", "screen"],
      [("screen -S work", "新建会话"), ("screen -r work", "恢复会话")], "中", "日常",
      None, "screen 较老牌；tmux 更现代，二者择一即可"),

    # ===== 新增补充：磁盘与文件系统 =====
    c("gdisk", "disk", "GPT 分区表交互工具", ["gpt分区", "gdisk"],
      [("gdisk /dev/sda", "交互管理 GPT 分区")], "中", "进阶",
      None, "gdisk 用于 GPT；fdisk 主要用于 MBR"),
    c("partprobe", "disk", "通知内核重读分区表", ["重读分区表", "partprobe"],
      [("partprobe /dev/sda", "分区后刷新内核")], "低", "日常",
      "分区后未 partprobe 可能导致设备节点未生成"),
    c("findmnt", "disk", "列出/查找已挂载文件系统", ["挂载查看", "findmnt"],
      [("findmnt", "树状显示挂载"), ("findmnt /mnt", "查某挂载点")], "中", "日常",
      None, "findmnt 信息比 mount 更易读，源自 util-linux"),
    c("hdparm", "disk", "查看/设置 IDE/SATA 盘参数", ["硬盘参数", "hdparm"],
      [("hdparm -I /dev/sda", "查看盘信息"), ("hdparm -t /dev/sda", "测顺序读速")], "低", "进阶",
      "写参数类选项有风险，只读查询更安全"),
    c("smartctl", "disk", "查看磁盘 SMART 健康", ["smart", "磁盘健康", "smartctl"],
      [("smartctl -a /dev/sda", "查看健康与属性"), ("smartctl -H /dev/sda", "整体健康自检")], "中", "日常"),
    c("cryptsetup", "disk", "管理 LUKS 磁盘加密", ["加密", "luks", "cryptsetup"],
      [("cryptsetup luksOpen /dev/sdb1 enc", "打开加密卷"), ("cryptsetup luksFormat /dev/sdb1", "格式化加密")], "低", "进阶",
      "luksFormat 会清空分区数据，确认无误再执行"),
    c("mountpoint", "disk", "判断目录是否为挂载点", ["挂载点判断", "mountpoint"],
      [("mountpoint /mnt", "返回是否为挂载点")], "低", "日常"),

    # ===== 新增补充：网络 =====
    c("ssh-keygen", "net", "生成/管理 SSH 密钥对", ["ssh密钥", "密钥生成", "ssh-keygen"],
      [("ssh-keygen -t ed25519 -C 'me@x.com'", "生成 Ed25519 密钥"), ("ssh-keygen -t rsa -b 4096", "生成 RSA 4096 密钥"), ("ssh-keygen -p -f ~/.ssh/id_rsa", "修改私钥密码")], "高", "日常",
      "私钥(~/.ssh/id_*)权限须为 600，过宽会被 ssh 拒绝"),
    c("ssh-copy-id", "net", "将公钥拷贝到远程主机", ["拷贝公钥", "ssh-copy-id"],
      [("ssh-copy-id user@host", "免密登录配置"), ("ssh-copy-id -i ~/.ssh/id_ed25519.pub user@host", "指定公钥")], "高", "日常"),
    c("telnet", "net", "Telnet 远程登录/端口探测", ["telnet", "端口测试"],
      [("telnet host 23", "登录远程"), ("telnet example.com 80", "手动探测 80 端口")], "中", "日常",
      "明文传输不安全，仅建议用于端口连通性测试"),
    c("hostname", "net", "查看/设置主机名", ["主机名", "hostname"],
      [("hostname", "显示主机名"), ("hostnamectl set-hostname web1", "永久设置(配合 systemd)")], "中", "日常",
      None, "hostname 临时改；持久改主机名用 hostnamectl(无 systemd 时改 /etc/hostname)"),
    c("nmcli", "net", "NetworkManager 命令行管理", ["网络管理", "nmcli"],
      [("nmcli device status", "查看网卡状态"), ("nmcli con up 'Wired'", "启用连接"), ("nmcli radio wifi off", "关 Wi-Fi")], "中", "日常"),
    c("iperf3", "net", "网络带宽性能测试", ["带宽测试", "iperf3"],
      [("iperf3 -s", "服务端"), ("iperf3 -c server", "客户端测速")], "中", "日常",
      "需两端分别起 -s 与 -c；防火墙放行端口"),
    c("ethtool", "net", "查看/配置网卡参数", ["网卡", "ethtool"],
      [("ethtool eth0", "查速率/双工"), ("ethtool -i eth0", "查驱动")], "低", "进阶"),
    c("resolvectl", "net", "systemd 解析服务查询/管理", ["dns解析", "resolvectl"],
      [("resolvectl query example.com", "DNS 查询"), ("resolvectl status", "查看解析状态")], "低", "日常",
      None, "无 systemd-resolved 的系统用 nslookup/dig 替代"),
    c("route", "net", "查看/设置路由表", ["路由", "route"],
      [("route -n", "数字形式显示路由"), ("route add default gw 192.168.1.1", "添加默认网关")], "中", "日常",
      None, "route 偏传统；现代多用 ip route"),
    c("ftp", "net", "FTP 文件传输客户端", ["ftp", "文件传输"],
      [("ftp ftp.example.com", "交互登录"), ("ftp> get file", "下载文件")], "低", "日常",
      "明文传输，敏感场景优先 scp/sftp"),
    c("nft", "net", "nftables 防火墙规则管理", ["防火墙", "nftables", "nft"],
      [("nft list ruleset", "查看规则"), ("nft add rule inet filter input tcp dport 22 accept", "放行 SSH")], "低", "进阶",
      None, "nftables 是 iptables 的现代替代；二者规则语法不兼容"),

    # ===== 新增补充：压缩与归档 =====
    c("cpio", "archive", "复制文件进出归档(cpio 格式)", ["cpio", "归档"],
      [("find . | cpio -o > a.cpio", "打包"), ("cpio -id < a.cpio", "解包")], "低", "进阶"),
    c("ar", "archive", "创建/管理静态库与 .deb 归档", ["归档", "静态库", "ar"],
      [("ar rcs lib.a a.o b.o", "打包静态库"), ("ar t lib.a", "列成员")], "低", "进阶"),
    c("bzcat", "archive", "不解压直接查看 .bz2 内容", ["bz2查看", "bzcat"],
      [("bzcat a.txt.bz2", "输出解压内容")], "低", "日常"),
    c("xzcat", "archive", "不解压直接查看 .xz 内容", ["xz查看", "xzcat"],
      [("xzcat a.txt.xz", "输出解压内容")], "低", "日常"),
    c("unxz", "archive", "解压 .xz 文件", ["xz解压", "unxz"],
      [("unxz a.txt.xz", "解压为 a.txt")], "低", "日常"),
    c("bunzip2", "archive", "解压 .bz2 文件", ["bz2解压", "bunzip2"],
      [("bunzip2 a.txt.bz2", "解压为 a.txt")], "低", "日常"),

    # ===== 新增补充：系统信息与监控 =====
    c("systemd-analyze", "sys", "分析系统与服务的启动耗时", ["启动分析", "systemd-analyze"],
      [("systemd-analyze", "总启动耗时"), ("systemd-analyze blame", "各服务耗时排序"), ("systemd-analyze critical-chain", "关键路径")], "低", "日常"),
    c("lsipc", "sys", "查看 IPC 资源(消息队列/信号量/共享内存)", ["ipc", "lsipc"],
      [("lsipc", "列出全部 IPC"), ("lsipc -m", "仅共享内存")], "低", "日常"),
    c("lslocks", "sys", "列出系统文件锁", ["文件锁", "lslocks"],
      [("lslocks", "查看当前锁")], "低", "日常"),
    c("lsns", "sys", "列出命名空间(namespaces)", ["命名空间", "lsns"],
      [("lsns", "列出全部 ns"), ("lsns -t pid", "按类型过滤")], "低", "日常"),
    c("pidstat", "sys", "按进程统计 CPU/内存/IO", ["进程统计", "pidstat"],
      [("pidstat 1", "每秒刷新"), ("pidstat -u -p 1234", "指定进程 CPU")], "中", "日常"),
    c("dstat", "sys", "综合资源实时监控(CPU/IO/网络)", ["综合监控", "dstat"],
      [("dstat", "默认多指标"), ("dstat -c -d -n 1", "CPU/磁盘/网络")], "中", "日常",
      None, "dstat 聚合了 vmstat/iostat/ifstat 等信息，一行看全"),

    # ===== 新增补充：软件包管理 =====
    c("apt-file", "pkg", "按文件名搜索所属软件包", ["包文件搜索", "apt-file"],
      [("apt-file update", "更新索引"), ("apt-file search bin/ls", "查命令所属包")], "低", "日常"),
    c("apt-mark", "pkg", "标记包为手动/自动安装", ["包标记", "apt-mark"],
      [("apt-mark manual nginx", "标记为手动"), ("apt-mark showhold", "查看被锁定的包")], "低", "日常"),

    # ===== 新增补充：内核模块 =====
    c("sysctl", "kernel", "运行时查看/设置内核参数", ["内核参数", "sysctl"],
      [("sysctl -a", "列出全部参数"), ("sysctl net.ipv4.ip_forward=1", "临时开启转发"), ("sysctl -p", "从 /etc/sysctl.conf 加载")], "中", "日常",
      "sysctl 直接修改仅临时生效；持久化需写入 /etc/sysctl.d/*.conf",
      "sysctl 对应 /proc/sys 下的内核运行参数"),
    c("update-initramfs", "kernel", "更新 Debian 系 initramfs", ["initramfs", "update-initramfs"],
      [("update-initramfs -u", "更新当前内核"), ("update-initramfs -c -k all", "全部重建")], "低", "进阶"),
    c("dracut", "kernel", "生成/管理 initramfs(通用)", ["initramfs", "dracut"],
      [("dracut", "为当前内核生成"), ("dracut -f", "覆盖生成")], "低", "进阶",
      None, "dracut 多见于 RHEL 系；Debian/Ubuntu 用 update-initramfs"),

    # ===== 新增补充：Shell 内建命令 =====
    c("bind", "shell", "绑定/查看 readline 按键映射(bash)", ["按键绑定", "bind"],
      [("bind -p", "查看绑定"), ("bind '\\C-f:forward-char'", "绑定 Ctrl+f 前进")], "低", "进阶"),
    c("compgen", "shell", "生成补全候选(bash 内建)", ["补全", "compgen"],
      [("compgen -c", "列出命令"), ("compgen -f", "列出文件")], "低", "进阶"),
    c("complete", "shell", "定义命令补全规则(bash 内建)", ["补全", "complete"],
      [("complete -c gcc", "按命令补全 gcc"), ("complete -F _my mcmd", "用函数补全")], "低", "进阶"),
    c("mapfile", "shell", "将输入读入数组(bash 内建)", ["读数组", "mapfile", "readarray"],
      [("mapfile -t arr < file.txt", "逐行读入数组"), ("mapfile -n 3 arr < f", "只读前3行")], "低", "进阶",
      None, "mapfile 别名 readarray；适合脚本中批量读行"),
    c("enable", "shell", "启用/停用内建命令(bash 内建)", ["内建开关", "enable"],
      [("enable -n echo", "临时禁用 echo 内建"), ("enable echo", "重新启用")], "低", "进阶"),
    c("help", "shell", "查看 bash 内建命令帮助", ["内建帮助", "help"],
      [("help cd", "查看 cd 内建说明"), ("help -m read", "详细格式")], "低", "入门",
      None, "help 仅对内建有效；外部命令用 man"),
    c("getopts", "shell", "解析命令行选项(bash 内建)", ["解析选项", "getopts"],
      [("while getopts ':ab:' o; do :; done", "循环读取 -a/-b")], "低", "进阶"),
    c("times", "shell", "显示进程累计 CPU 时间(bash 内建)", ["cpu时间", "times"],
      [("times", "打印 shell 及子进程耗时")], "低", "日常"),

    # ===== 新增补充：编辑器与工具 =====
    c("xargs", "editor", "将标准输入转为命令参数", ["参数构造", "xargs"],
      [("find . -name '*.log' | xargs rm", "批量删除"), ("cat list | xargs -I{} cp {} /bak", "逐个拷贝"), ("xargs -P4 -n1 cmd", "并行4路")], "高", "日常",
      "文件名含空格/换行易出错，建议配合 find -print0 | xargs -0",
      "xargs 把输入拼成参数；并行能力弱于 GNU parallel"),
    c("env", "editor", "在指定环境中运行命令", ["环境变量", "env"],
      [("env", "打印全部环境变量"), ("env VAR=1 cmd", "临时设变量运行"), ("env -i bash", "清空环境启动")], "中", "日常"),
    c("printenv", "editor", "打印环境变量", ["打印环境", "printenv"],
      [("printenv", "列出全部"), ("printenv PATH", "查看单个")], "中", "日常",
      None, "printenv 专注环境变量；set 还能看 shell 变量与函数"),
    c("seq", "editor", "生成整数数列", ["数列", "seq"],
      [("seq 1 5", "1 到 5"), ("seq -w 1 10", "等宽补零"), ("seq 2 2 10", "步长2")], "中", "日常"),
    c("expr", "editor", "计算表达式(算术/字符串)", ["表达式", "expr"],
      [("expr 3 + 5", "算术"), ("expr length 'abc'", "字符串长度"), ("expr 'a.txt' : '.*\\.txt'", "匹配 .txt 结尾")], "中", "日常",
      "运算符两侧需空格；乘号 * 要转义或用引号",
      "expr 较老旧；脚本里优先用 $(( )) 做算术"),
    c("xdg-open", "editor", "用默认程序打开文件/URL", ["打开文件", "xdg-open"],
      [("xdg-open report.pdf", "用默认程序打开"), ("xdg-open https://x.com", "浏览器打开")], "低", "日常"),
    c("apropos", "editor", "按关键字搜索手册页", ["手册搜索", "apropos"],
      [("apropos network", "搜含 network 的手册"), ("apropos -a copy file", "同时满足多关键词")], "中", "日常",
      None, "apropos 等价于 man -k"),
    c("gpg", "editor", "加密/签名与密钥管理(GnuPG)", ["加密", "签名", "gpg"],
      [("gpg -c file", "对称加密"), ("gpg -d file.gpg", "解密"), ("gpg --gen-key", "生成密钥对"), ("gpg --verify file.sig", "验证签名")], "中", "进阶",
      "私钥务必备份；--armor 生成文本格式(.asc)便于传输"),
]

GIT = [
    # ---- 仓库与配置 ----
    c("git init", "g_config", "初始化仓库", ["初始化", "仓库", "git init"],
      [("git init", "当前目录建仓库"), ("git init --bare", "建裸仓库（服务端）")], "高", "入门"),
    c("git clone", "g_config", "克隆仓库", ["克隆", "git clone"],
      [("git clone url", "克隆到同名目录"), ("git clone -b dev url", "克隆指定分支")], "高", "入门"),
    c("git config", "g_config", "配置", ["配置", "git config"],
      [("git config --global user.name 'x'", "设用户名"), ("git config --list", "查看配置")], "高", "入门"),
    c("git help", "g_config", "查看帮助", ["帮助", "git help"],
      [("git help commit", "看 commit 手册")], "中", "入门"),
    c("git var", "g_config", "显示 git 变量", ["变量", "git var"],
      [("git var GIT_AUTHOR_IDENT", "看作者身份")], "低", "进阶"),
    c("git version", "g_config", "显示版本", ["版本", "git version"],
      [("git version", "查看 git 版本")], "低", "入门"),
    c("git bugreport", "g_config", "生成缺陷报告", ["缺陷报告", "git bugreport"],
      [("git bugreport", "生成环境报告")], "低", "日常"),

    # ---- 暂存与提交 ----
    c("git status", "g_commit", "查看状态", ["状态", "git status"],
      [("git status", "看改动"), ("git status -s", "紧凑状态")], "高", "入门"),
    c("git add", "g_commit", "暂存改动", ["暂存", "git add"],
      [("git add .", "暂存全部"), ("git add -p", "交互暂存")], "高", "入门",
      "add . 会暂存所有，含敏感文件，注意 .gitignore"),
    c("git commit", "g_commit", "提交", ["提交", "git commit"],
      [("git commit -m 'msg'", "提交"), ("git commit --amend", "修改上次提交")], "高", "入门"),
    c("git rm", "g_commit", "删除并暂存", ["删除", "git rm"],
      [("git rm f.txt", "删文件并暂存")], "中", "入门"),
    c("git mv", "g_commit", "移动/重命名并暂存", ["移动", "git mv"],
      [("git mv a.txt b.txt", "重命名")], "中", "入门"),
    c("git clean", "g_commit", "删除未跟踪文件", ["清理", "git clean"],
      [("git clean -fd", "删未跟踪文件/目录"), ("git clean -n", "预览")], "中", "日常",
      "-fd 不可恢复，先 -n 预览"),
    c("git stage", "g_commit", "add 别名", ["暂存", "git stage"],
      [("git stage .", "同 add")], "低", "日常", None, "git stage 是 git add 的别名"),

    # ---- 查看与比较 ----
    c("git log", "g_view", "查看提交历史", ["历史", "git log"],
      [("git log", "默认历史"), ("git log --oneline --graph --all", "图形化")], "高", "入门"),
    c("git show", "g_view", "显示对象内容", ["显示", "git show"],
      [("git show", "看最近提交"), ("git show <sha>", "看某提交")], "高", "日常"),
    c("git diff", "g_view", "查看差异", ["差异", "git diff"],
      [("git diff", "工作区 vs 暂存"), ("git diff --staged", "暂存 vs 上次提交")], "高", "入门"),
    c("git blame", "g_view", "逐行标注作者", ["溯源", "git blame"],
      [("git blame f.txt", "看每行作者")], "中", "日常"),
    c("git grep", "g_view", "仓库内搜索", ["搜索", "git grep"],
      [("git grep 'func'", "在版本库搜")], "中", "日常"),
    c("git shortlog", "g_view", "按作者汇总提交", ["汇总", "git shortlog"],
      [("git shortlog -sn", "各作者提交数")], "低", "日常"),
    c("git describe", "g_view", "用标签描述提交", ["描述", "git describe"],
      [("git describe --tags", "最近标签+偏移")], "低", "日常"),
    c("git reflog", "g_view", "引用日志（含丢失提交）", ["引用日志", "git reflog"],
      [("git reflog", "看 HEAD 变动历史")], "中", "进阶",
      "误删提交可用 reflog 找回"),
    c("git whatchanged", "g_view", "显示提交改动文件", ["改动", "git whatchanged"],
      [("git whatchanged -p", "类 log 加补丁")], "低", "日常", None, "类似 git log 但侧重文件列表"),
    c("git difftool", "g_view", "用外部对比工具查看差异", ["外部对比", "difftool", "vimdiff", "meld"],
      [("git difftool", "用工具看工作区与暂存差异"), ("git difftool HEAD~1", "对比上一次提交")], "中", "日常",
      "需先配置 diff.tool（git config --global diff.tool vimdiff）；可视为图形化的 git diff"),

    # ---- 分支与合并 ----
    c("git branch", "g_branch", "分支管理", ["分支", "git branch"],
      [("git branch", "列分支"), ("git branch -d feat", "删已合并分支")], "高", "入门"),
    c("git switch", "g_branch", "切换/新建分支", ["切换分支", "git switch"],
      [("git switch main", "切换"), ("git switch -c feat", "新建并切换")], "高", "日常", None,
      "switch 专用于分支（2.23+），比 checkout 清晰"),
    c("git checkout", "g_branch", "切换分支/恢复文件", ["检出", "撤销改动", "git checkout"],
      [("git checkout main", "切分支"), ("git checkout -- f.txt", "丢弃改动")], "高", "日常",
      "checkout -- 丢弃改动不可恢复；切分支用 switch 更安全"),
    c("git merge", "g_branch", "合并分支", ["合并", "git merge"],
      [("git merge feat", "合并 feat 到当前"), ("git merge --no-ff feat", "保留合并点")], "高", "日常"),
    c("git mergetool", "g_branch", "图形化解决冲突", ["解决冲突", "git mergetool"],
      [("git mergetool", "启动合并工具")], "中", "进阶"),
    c("git rebase", "g_branch", "变基", ["变基", "git rebase"],
      [("git rebase main", "把当前变基到 main"), ("git rebase -i HEAD~3", "交互整理")], "中", "进阶",
      "已推送的提交勿 rebase，会改写历史"),
    c("git cherry-pick", "g_branch", "复制某次提交", ["遴选", "git cherry-pick"],
      [("git cherry-pick <sha>", "复制到当前分支")], "中", "进阶"),
    c("git tag", "g_branch", "打标签", ["标签", "git tag"],
      [("git tag v1.0", "轻量标签"), ("git tag -a v1.0 -m 'rel'", "附注标签")], "中", "日常"),
    c("git range-diff", "g_branch", "比较两个提交区间", ["区间差异", "git range-diff"],
      [("git range-diff A..B C..D", "比较两区间")], "低", "进阶"),
    c("git merge-tree", "g_branch", "预览合并结果（不改动仓库）", ["预览合并", "merge-tree", "冲突检测"],
      [("git merge-tree --write-tree main feat", "计算合并树并报告冲突"), ("git merge-tree main feat", "纯文本合并输出")], "低", "进阶",
      "常用于 CI 检测能否无冲突合并；不修改工作区与提交历史"),

    # ---- 远程协作 ----
    c("git remote", "g_remote", "远程仓库管理", ["远程", "git remote"],
      [("git remote add origin url", "加远程"), ("git remote -v", "看远程")], "高", "入门"),
    c("git fetch", "g_remote", "拉取但不合并", ["拉取", "git fetch"],
      [("git fetch origin", "取远端更新"), ("git fetch -p", "删过时远程分支")], "高", "日常"),
    c("git pull", "g_remote", "拉取并合并", ["拉取合并", "git pull"],
      [("git pull", "拉取并合并"), ("git pull --rebase", "变基式拉取")], "高", "日常",
      "pull 等价于 fetch+merge；用 --rebase 减少合并提交"),
    c("git push", "g_remote", "推送", ["推送", "git push"],
      [("git push -u origin main", "首次推送并关联"), ("git push --force-with-lease", "安全强推")], "高", "日常",
      "已推送的历史勿强推；必须时用 --force-with-lease"),
    c("git submodule", "g_remote", "子模块", ["子模块", "git submodule"],
      [("git submodule add url lib", "加子模块"), ("git submodule update --init", "初始化")], "低", "进阶"),
    c("git worktree", "g_remote", "多工作树", ["工作树", "git worktree"],
      [("git worktree add ../wt main", "另开一个分支目录")], "低", "进阶"),
    c("git bundle", "g_remote", "打包为单文件", ["打包", "git bundle"],
      [("git bundle create r.bundle --all", "离线传输用")], "低", "进阶"),
    c("git request-pull", "g_remote", "生成拉取请求说明", ["拉取请求", "git request-pull"],
      [("git request-pull base origin", "生成说明")], "低", "日常"),
    c("git ls-remote", "g_remote", "列出远程仓库的引用", ["列出远程", "ls-remote", "查看分支", "查看标签"],
      [("git ls-remote origin", "看远程分支与标签"), ("git ls-remote --heads origin", "仅看分支")], "中", "日常",
      "不拉取数据即可查看远端有哪些分支/标签，便于确认远程状态"),

    # ---- 撤销与重置 ----
    c("git reset", "g_undo", "重置", ["重置", "撤销提交", "git reset"],
      [("git reset --soft HEAD~1", "撤提交留改动"), ("git reset --hard HEAD~1", "彻底丢弃")], "高", "日常",
      "--hard 丢弃工作区改动，不可恢复；优先 --soft/--mixed"),
    c("git restore", "g_undo", "恢复工作区/暂存", ["恢复", "撤销改动", "git restore"],
      [("git restore --staged f", "移出暂存"), ("git restore f", "丢弃工作区改动")], "高", "日常", None,
      "restore 专用于恢复（2.23+），语义清晰"),
    c("git revert", "g_undo", "反向提交", ["撤销", "撤销提交", "git revert"],
      [("git revert <sha>", "生成抵消提交")], "中", "日常", None,
      "revert 不改历史，适合已推送；reset 改历史"),
    c("git stash", "g_undo", "暂存快照", ["暂存快照", "git stash"],
      [("git stash push -m 'wip'", "暂存"), ("git stash pop", "恢复并删除")], "中", "日常"),

    # ---- 补丁与邮件 ----
    c("git format-patch", "g_patch", "生成补丁邮件", ["生成补丁", "git format-patch"],
      [("git format-patch origin/main", "生成一系列 .patch")], "低", "进阶"),
    c("git am", "g_patch", "应用邮件补丁", ["应用补丁", "git am"],
      [("git am *.patch", "应用 mbox 补丁")], "低", "进阶"),
    c("git apply", "g_patch", "应用 diff 补丁", ["应用补丁", "git apply"],
      [("git apply p.patch", "应用补丁")], "低", "日常", None, "apply 不动提交；am 会创建提交"),
    c("git send-email", "g_patch", "发送补丁邮件", ["发送邮件", "git send-email"],
      [("git send-email *.patch", "发到邮件列表")], "低", "进阶"),
    c("git imap-send", "g_patch", "经 IMAP 发补丁", ["IMAP发送", "git imap-send"],
      [("git imap-send *.patch", "通过 IMAP 发送")], "低", "进阶"),
    c("git mailinfo", "g_patch", "提取邮件补丁信息", ["邮件信息", "git mailinfo"],
      [("git mailinfo msg patch < m", "解析邮件")], "低", "进阶"),

    # ---- 调试 ----
    c("git bisect", "g_debug", "二分定位引入问题的提交", ["二分查找", "git bisect"],
      [("git bisect start", "开始"), ("git bisect bad/good <sha>", "标记"), ("git bisect run ./test.sh", "自动")], "低", "进阶"),

    # ---- 维护 ----
    c("git gc", "g_maint", "垃圾回收", ["垃圾回收", "git gc"],
      [("git gc", "压缩对象")], "低", "日常"),
    c("git fsck", "g_maint", "检查对象库", ["检查", "git fsck"],
      [("git fsck", "校验完整性")], "低", "进阶"),
    c("git prune", "g_maint", "删除不可达对象", ["清理", "git prune"],
      [("git prune", "删悬空对象")], "低", "进阶"),
    c("git repack", "g_maint", "重新打包对象", ["重新打包", "git repack"],
      [("git repack -ad", "打包并删冗余")], "低", "进阶"),
    c("git maintenance", "g_maint", "后台维护", ["维护", "git maintenance"],
      [("git maintenance start", "开启定时维护")], "低", "日常"),
    c("git count-objects", "g_maint", "统计对象", ["统计", "git count-objects"],
      [("git count-objects -v", "详细统计")], "低", "日常"),
    c("git check-ignore", "g_maint", "检查文件为何被忽略", ["忽略检查", "check-ignore", ".gitignore", "调试"],
      [("git check-ignore a.log", "看 a.log 是否被忽略"), ("git check-ignore -v a.log", "显示命中的忽略规则")], "中", "日常",
      "-v 可定位是 .gitignore 的哪一行生效，调试忽略规则非常实用"),

    # ---- 脚本与其他 ----
    c("git archive", "g_other", "导出快照", ["导出", "git archive"],
      [("git archive --format=zip HEAD > t.zip", "导出当前")], "低", "日常"),
    c("git check-attr", "g_other", "查询文件的 gitattributes 属性", ["属性查询", "check-attr", "gitattributes"],
      [("git check-attr text a.txt", "查 text 属性值"), ("git check-attr -a a.txt", "查全部属性")], "低", "进阶"),
    c("git svn", "g_other", "与 Subversion 仓库双向同步", ["svn同步", "git svn", "迁移", "svn"],
      [("git svn clone svn://host/repo", "克隆 SVN 仓库为 git"), ("git svn fetch", "拉取 SVN 更新"), ("git svn dcommit", "推送提交到 SVN")], "低", "进阶",
      "用于从 SVN 迁移；dcommit 会把本地提交逐条转为 SVN 提交"),
    c("git ls-files", "g_other", "列出跟踪文件", ["列出文件", "git ls-files"],
      [("git ls-files", "看已跟踪文件")], "低", "日常"),
    c("git rev-parse", "g_other", "解析修订/路径", ["解析", "git rev-parse"],
      [("git rev-parse HEAD", "得完整 SHA"), ("git rev-parse --show-toplevel", "仓库根")], "低", "进阶"),
    c("git rev-list", "g_other", "列出提交对象", ["列出提交", "git rev-list"],
      [("git rev-list --count HEAD", "提交数")], "低", "进阶"),

    # ---- 底层命令 plumbing ----
    c("git cat-file", "g_plumb", "查看对象内容/类型", ["对象查看", "git cat-file"],
      [("git cat-file -p <sha>", "看对象内容"), ("git cat-file -t <sha>", "看类型")], "低", "进阶"),
    c("git hash-object", "g_plumb", "计算/写入对象哈希", ["哈希", "git hash-object"],
      [("git hash-object f.txt", "得 SHA-1")], "低", "进阶"),
    c("git update-index", "g_plumb", "操作索引", ["索引", "git update-index"],
      [("git update-index --add f", "加入索引")], "低", "进阶"),
    c("git write-tree", "g_plumb", "把索引写成树对象", ["写树", "git write-tree"],
      [("git write-tree", "生成树 SHA")], "低", "进阶"),
    c("git commit-tree", "g_plumb", "创建提交对象", ["创建提交", "git commit-tree"],
      [("git commit-tree <tree> -p <parent> -m 'm'", "造提交")], "低", "进阶"),
    c("git update-ref", "g_plumb", "更新引用", ["更新引用", "git update-ref"],
      [("git update-ref refs/heads/x <sha>", "设分支指向")], "低", "进阶"),
    c("git show-ref", "g_plumb", "列出引用", ["列出引用", "git show-ref"],
      [("git show-ref", "看所有引用")], "低", "进阶"),
    c("git symbolic-ref", "g_plumb", "读写符号引用", ["符号引用", "git symbolic-ref"],
      [("git symbolic-ref HEAD refs/heads/main", "设 HEAD")], "低", "进阶"),
    c("git name-rev", "g_plumb", "把 SHA 映射为引用名", ["名称映射", "git name-rev"],
      [("git name-rev <sha>", "得分支/标签名")], "低", "进阶"),
    c("git for-each-ref", "g_plumb", "迭代引用", ["引用迭代", "git for-each-ref"],
      [("git for-each-ref --format='%(refname)'", "列引用")], "低", "进阶"),
    c("git verify-pack", "g_plumb", "校验 pack 文件", ["校验pack", "git verify-pack"],
      [("git verify-pack -v f.pack", "详细校验")], "低", "进阶"),
    c("git pack-objects", "g_plumb", "打包对象", ["打包对象", "git pack-objects"],
      [("git pack-objects out < objs", "生成 pack")], "低", "进阶"),
    c("git index-pack", "g_plumb", "建 pack 索引", ["pack索引", "git index-pack"],
      [("git index-pack f.pack", "生成 idx")], "低", "进阶"),
    c("git unpack-objects", "g_plumb", "解包到对象库", ["解包", "git unpack-objects"],
      [("git unpack-objects < f.pack", "解包")], "低", "进阶"),
    c("git pack-refs", "g_plumb", "打包引用", ["打包引用", "git pack-refs"],
      [("git pack-refs --all", "压缩 refs")], "低", "进阶"),
    c("git read-tree", "g_plumb", "读树到索引", ["读树", "git read-tree"],
      [("git read-tree <tree>", "载入索引")], "低", "进阶"),
    c("git ls-tree", "g_plumb", "列树对象内容", ["列树", "git ls-tree"],
      [("git ls-tree HEAD", "看根树")], "低", "进阶"),
    c("git mktree", "g_plumb", "由 ls-tree 输出建树", ["建树", "git mktree"],
      [("git ls-tree HEAD | git mktree", "重建树")], "低", "进阶"),
    c("git notes", "g_plumb", "给提交加附注", ["附注", "git notes"],
      [("git notes add -m 'x' <sha>", "加注")], "低", "进阶"),
    c("git replace", "g_plumb", "替换对象", ["替换对象", "git replace"],
      [("git replace <sha> <sha2>", "临时替换")], "低", "进阶"),

    # ---- 进阶工作流 ----
    c("git filter-repo", "g_adv", "重写历史（推荐）", ["重写历史", "git filter-repo"],
      [("git filter-repo --path dir/", "只保留某目录历史")], "低", "进阶",
      "破坏性操作，先备份；取代已弃用 filter-branch"),
    c("git filter-branch", "g_adv", "重写历史（已弃用）", ["重写历史", "git filter-branch"],
      [("git filter-branch --tree-filter '...' HEAD", "改写")], "低", "进阶",
      "已弃用，优先 filter-repo；慢且易错"),
    c("git subtree", "g_adv", "子树合并", ["子树", "git subtree"],
      [("git subtree add --prefix=lib url", "嵌入子项目")], "低", "进阶"),
    c("git sparse-checkout", "g_adv", "稀疏检出", ["稀疏检出", "git sparse-checkout"],
      [("git sparse-checkout set src/", "只检某目录")], "低", "进阶"),
    c("git rerere", "g_adv", "重用冲突解决", ["重用解决", "git rerere"],
      [("git config rerere.enabled true", "开启")], "低", "进阶"),
    c("git instaweb", "g_adv", "启动 Web 界面", ["web界面", "git instaweb"],
      [("git instaweb", "本地起 gitweb")], "低", "日常"),
    c("git credential", "g_adv", "凭证管理", ["凭证", "git credential"],
      [("git config credential.helper store", "明文存密码")], "低", "日常",
      "store 明文存密码不安全，推荐 cache/osxkeychain"),
    c("git fast-export", "g_adv", "导出为流", ["导出流", "git fast-export"],
      [("git fast-export --all", "导出供迁移")], "低", "进阶"),
    c("git fast-import", "g_adv", "从流导入", ["导入流", "git fast-import"],
      [("git fast-import < stream", "导入")], "低", "进阶"),

    # ---- 传输与服务 ----
    c("git daemon", "g_transport", "匿名 Git 服务", ["git服务", "git daemon"],
      [("git daemon --base-path=/repos", "起只读服务")], "低", "进阶"),
    c("git upload-pack", "g_transport", "上传对象（拉取端）", ["上传", "git upload-pack"],
      [("git upload-pack repo", "被 fetch 调用")], "低", "进阶"),
    c("git receive-pack", "g_transport", "接收对象（推送端）", ["接收", "git receive-pack"],
      [("git receive-pack repo", "被 push 调用")], "低", "进阶"),
    c("git http-backend", "g_transport", "CGI 智能 HTTP", ["http后端", "git http-backend"],
      [("git http-backend", "配合 web 服务器")], "低", "进阶"),
    c("git send-pack", "g_transport", "推送引用", ["推送", "git send-pack"],
      [("git send-pack origin main", "底层 push")], "低", "进阶"),
    c("git shell", "g_transport", "受限登录 shell", ["受限shell", "git shell"],
      [("git shell", "仅允许 git 操作")], "低", "进阶"),
    c("git upload-archive", "g_transport", "支持 git archive 远程", ["archive远程", "git upload-archive"],
      [("git upload-archive repo", "配合 archive")], "低", "进阶"),

    # ===== 新增补充：Git =====
    c("git cherry", "g_branch", "列出尚未合并到上游的提交", ["cherry", "未合并提交"],
      [("git cherry", "对比当前分支与上游"), ("git cherry origin/main", "指定上游比较")], "中", "日常"),
    c("git show-branch", "g_branch", "展示分支提交历史/对比分支", ["show-branch", "分支对比"],
      [("git show-branch", "当前分支提交"), ("git show-branch main dev", "对比两分支")], "低", "进阶"),
    c("git verify-commit", "g_debug", "验证提交 GPG 签名", ["签名验证", "verify-commit"],
      [("git verify-commit HEAD", "校验最新提交签名")], "低", "进阶"),
    c("git verify-tag", "g_debug", "验证标签 GPG 签名", ["标签签名", "verify-tag"],
      [("git verify-tag v1.0.0", "校验标签签名")], "低", "进阶"),
]


def main():
    data = {"categories": CATEGORIES, "commands": LINUX + GIT}
    json_path = os.path.join(DATA_DIR, "commands.json")
    js_path = os.path.join(DATA_DIR, "commands.js")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("window.COMMAND_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";")
    linux_n = sum(1 for x in data["commands"] if x["category"] in {c["id"] for c in CATEGORIES if c["group"] == "linux"})
    git_n = sum(1 for x in data["commands"] if x["category"] in {c["id"] for c in CATEGORIES if c["group"] == "git"})
    print("OK ->", json_path)
    print("Linux 命令数:", linux_n)
    print("Git   命令数:", git_n)
    print("合计:", len(data["commands"]))


if __name__ == "__main__":
    main()
