# -*- coding: utf-8 -*-
"""生成命令数据集 data/commands.json 与 data/commands.js

数据来源：
- Linux 命令：linux-commands-cheatsheet.pdf（Linuxize）提取的常用命令集，并补充分类扩展
- Git 命令：progit.pdf（Pro Git 官方手册）文档化的命令范围
命令均含中文说明、频率（高/中/低）、难度（入门/日常/进阶）、中文关键词、使用案例，
高频/易错命令额外含 pitfalls（易错警告）与 compare（命令对比）。
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA_DIR = os.path.join(ROOT, "data")
os.makedirs(DATA_DIR, exist_ok=True)

# 分类：group 用于区分 Linux / Git 两大体系
CATEGORIES = [
    {"id": "file", "name": "文件与目录操作", "group": "linux"},
    {"id": "view", "name": "文件查看", "group": "linux"},
    {"id": "text", "name": "文本处理", "group": "linux"},
    {"id": "perm", "name": "文件权限与属性", "group": "linux"},
    {"id": "user", "name": "用户与用户组", "group": "linux"},
    {"id": "proc", "name": "进程管理", "group": "linux"},
    {"id": "disk", "name": "磁盘与文件系统", "group": "linux"},
    {"id": "net", "name": "网络", "group": "linux"},
    {"id": "archive", "name": "压缩与归档", "group": "linux"},
    {"id": "sys", "name": "系统信息与监控", "group": "linux"},
    {"id": "power", "name": "关机与系统控制", "group": "linux"},
    {"id": "pkg", "name": "软件包管理", "group": "linux"},
    {"id": "kernel", "name": "内核模块", "group": "linux"},
    {"id": "shell", "name": "Shell 内建命令", "group": "linux"},
    {"id": "editor", "name": "编辑器与工具", "group": "linux"},
    {"id": "g_config", "name": "仓库与配置", "group": "git"},
    {"id": "g_commit", "name": "暂存与提交", "group": "git"},
    {"id": "g_view", "name": "查看与比较", "group": "git"},
    {"id": "g_branch", "name": "分支与合并", "group": "git"},
    {"id": "g_remote", "name": "远程协作", "group": "git"},
    {"id": "g_undo", "name": "撤销与重置", "group": "git"},
    {"id": "g_patch", "name": "补丁与邮件", "group": "git"},
    {"id": "g_debug", "name": "调试", "group": "git"},
    {"id": "g_maint", "name": "维护", "group": "git"},
    {"id": "g_other", "name": "脚本与其他", "group": "git"},
    {"id": "g_plumb", "name": "底层命令 plumbing", "group": "git"},
    {"id": "g_adv", "name": "进阶工作流", "group": "git"},
    {"id": "g_transport", "name": "传输与服务", "group": "git"},
]


def c(name, cat, desc, kws, ex, freq, diff, pit=None, cmp=None):
    return {
        "name": name,
        "category": cat,
        "description": desc,
        "keywords": kws,
        "examples": [{"cmd": e[0], "desc": e[1]} for e in ex],
        "frequency": freq,
        "difficulty": diff,
        "pitfalls": pit,
        "compare": cmp,
    }


LINUX = [
    # ---- 文件与目录操作 ----
    c("ls", "file", "列出目录内容", ["列出", "目录", "文件列表", "ls"],
      [("ls -la", "长格式显示全部文件（含隐藏文件）"), ("ls -lh", "以人类可读大小显示")], "高", "入门",
      "默认不显示隐藏文件（以 . 开头），需加 -a", "ls 列目录；ll 多为 ls -l 别名"),
    c("cd", "file", "切换工作目录", ["切换", "目录", "cd"],
      [("cd ~", "回到家目录"), ("cd -", "回到上次所在目录")], "高", "入门"),
    c("pwd", "file", "显示当前目录绝对路径", ["当前目录", "路径", "pwd"],
      [("pwd", "打印工作目录"), ("pwd -P", "解析符号链接后的真实路径")], "高", "入门"),
    c("cp", "file", "复制文件或目录", ["复制", "拷贝", "cp"],
      [("cp a.txt b.txt", "复制文件"), ("cp -r src/ dst/", "递归复制目录")], "高", "入门",
      "复制目录必须加 -r，否则报错"),
    c("mv", "file", "移动或重命名", ["移动", "重命名", "mv"],
      [("mv a.txt b.txt", "重命名文件"), ("mv f.txt dir/", "移动到目录")], "高", "入门"),
    c("rm", "file", "删除文件或目录", ["删除", "移除", "rm"],
      [("rm file.txt", "删除文件"), ("rm -rf dir", "递归强制删除目录（危险）")], "高", "入门",
      "rm -rf / 或 rm -rf ~ 会销毁系统/家目录数据，务必先确认路径"),
    c("mkdir", "file", "创建目录", ["创建目录", "新建文件夹", "mkdir"],
      [("mkdir foo", "创建单级目录"), ("mkdir -p a/b/c", "递归创建多级目录")], "高", "入门",
      "父目录不存在时需 -p，否则失败"),
    c("rmdir", "file", "删除空目录", ["删除空目录", "rmdir"],
      [("rmdir empty/", "删除空目录")], "中", "入门", None, "rmdir 仅删空目录；rm -r 可删非空目录"),
    c("touch", "file", "创建空文件或更新时间戳", ["创建文件", "时间戳", "touch"],
      [("touch new.txt", "新建空文件"), ("touch -c old.txt", "仅更新时间不新建")], "高", "入门"),
    c("find", "file", "按条件查找文件", ["查找文件", "搜索", "find"],
      [("find . -name '*.py'", "按名查找"), ("find . -mtime -7", "查找 7 天内修改的文件")], "高", "日常",
      "路径放最前；-delete 误用会删文件，先不加该参数确认"),
    c("ln", "file", "创建链接", ["链接", "软链接", "硬链接", "ln"],
      [("ln -s target link", "创建软链接"), ("ln f hard", "创建硬链接")], "中", "日常",
      "软链接用 -s；源路径建议用绝对路径，否则移动后失效", None),
    c("readlink", "file", "查看链接指向", ["链接指向", "readlink"],
      [("readlink link", "打印链接目标")], "低", "日常"),
    c("realpath", "file", "解析为绝对路径", ["绝对路径", "realpath"],
      [("realpath f.txt", "输出规范绝对路径")], "低", "日常"),
    c("basename", "file", "取路径中的文件名", ["文件名", "basename"],
      [("basename /a/b/c.txt", "得到 c.txt")], "低", "日常"),
    c("dirname", "file", "取路径中的目录部分", ["目录名", "dirname"],
      [("dirname /a/b/c.txt", "得到 /a/b")], "低", "日常"),
    c("tree", "file", "树状显示目录结构", ["树状", "目录结构", "tree"],
      [("tree -L 2", "显示两层"), ("tree -a", "包含隐藏文件")], "中", "日常"),
    c("stat", "file", "显示文件详细状态", ["文件状态", "stat"],
      [("stat file.txt", "查看大小/权限/时间")], "中", "日常"),
    c("file", "file", "识别文件类型", ["文件类型", "file"],
      [("file a.bin", "识别为 ELF/文本等")], "中", "日常"),
    c("tee", "file", "输出到屏幕并写入文件", ["分流输出", "tee"],
      [("cmd | tee out.txt", "既显示又保存"), ("cmd | tee -a out.txt", "追加保存")], "中", "日常",
      "默认覆盖目标文件，追加需 -a"),
    c("pushd", "file", "压入目录栈并切换", ["目录栈", "pushd"],
      [("pushd dir", "切换并压栈")], "低", "日常"),
    c("popd", "file", "弹出目录栈", ["目录栈", "popd"],
      [("popd", "回到上一个目录")], "低", "日常"),

    # ---- 文件查看 ----
    c("cat", "view", "查看/拼接文件内容", ["查看文件", "拼接", "cat"],
      [("cat f.txt", "打印全部内容"), ("cat a b > c", "拼接两文件")], "高", "入门",
      "大文件会刷屏，改用 less"),
    c("less", "view", "分页查看文件", ["分页查看", "less"],
      [("less f.txt", "上下翻页查看")], "高", "入门", None, "less 可上下翻；more 基本只能下翻"),
    c("more", "view", "逐屏查看文件", ["逐屏查看", "more"],
      [("more f.txt", "逐屏显示")], "中", "入门"),
    c("head", "view", "查看文件开头", ["开头", "head"],
      [("head -n 20 f", "看前 20 行"), ("head -c 100 f", "看前 100 字节")], "高", "入门"),
    c("tail", "view", "查看文件末尾", ["末尾", "tail"],
      [("tail -n 20 f", "看后 20 行"), ("tail -f f", "实时跟踪新增内容")], "高", "入门",
      "跟踪日志首选 tail -f"),
    c("nl", "view", "带行号输出", ["行号", "nl"],
      [("nl f.txt", "输出带行号")], "低", "日常"),
    c("tac", "view", "逆序输出行", ["逆序", "tac"],
      [("tac f.txt", "从末尾到开头")], "低", "日常"),
    c("od", "view", "八进制/十六进制查看", ["二进制查看", "od"],
      [("od -c f", "以字符显示")], "低", "进阶"),
    c("xxd", "view", "十六进制转储", ["十六进制", "xxd"],
      [("xxd f.bin", "十六进制+ASCII")], "低", "进阶"),
    c("hexdump", "view", "十六进制转储", ["十六进制", "hexdump"],
      [("hexdump -C f", "规范十六进制格式")], "低", "进阶"),
    c("strings", "view", "提取可打印字符串", ["字符串", "strings"],
      [("strings a.out", "查看二进制中的字符串")], "低", "进阶"),
    c("fold", "view", "按宽度折行", ["折行", "fold"],
      [("fold -w 80 f", "每行 80 列")], "低", "日常"),
    c("pr", "view", "格式化分页输出", ["格式化", "pr"],
      [("pr f.txt", "加页眉分页")], "低", "日常"),

    # ---- 文本处理 ----
    c("grep", "text", "文本搜索", ["搜索文本", "匹配", "grep"],
      [("grep -rn 'TODO' src/", "递归搜索含 TODO 的文件"), ("grep -i error log", "忽略大小写")], "高", "入门",
      "正则默认识别基础语法；用 -E 启用扩展正则", None),
    c("egrep", "text", "扩展正则搜索（=grep -E）", ["扩展正则", "egrep"],
      [("egrep 'a|b' f", "匹配 a 或 b")], "中", "日常", None, "egrep 等价于 grep -E"),
    c("fgrep", "text", "固定字符串搜索（=grep -F）", ["固定字符串", "fgrep"],
      [("fgrep 'a$b' f", "按字面量匹配")], "低", "日常", None, "fgrep 不解释正则，等价于 grep -F"),
    c("sed", "text", "流编辑器", ["流编辑", "替换", "sed"],
      [("sed 's/foo/bar/g' f", "全局替换"), ("sed -i 's/a/b/g' f", "就地修改文件")], "高", "日常",
      "-i 直接改文件，先备份；macOS 需 -i ''"),
    c("awk", "text", "文本处理语言", ["字段处理", "awk"],
      [("awk '{print $1}' f", "打印第一列"), ("awk -F: '$3>100' /etc/passwd", "按 : 分割筛选")], "高", "进阶",
      "默认空格分隔；$0 整行、$1 第一列"),
    c("sort", "text", "排序", ["排序", "sort"],
      [("sort f.txt", "字典序排序"), ("sort -n -k2 f", "按第 2 列数值排序")], "高", "日常"),
    c("uniq", "text", "去重（需先排序）", ["去重", "uniq"],
      [("sort f | uniq", "去重"), ("uniq -c", "统计出现次数")], "高", "日常",
      "uniq 只去相邻重复，通常先 sort"),
    c("cut", "text", "按列截取", ["截取列", "cut"],
      [("cut -d: -f1 /etc/passwd", "取第一字段"), ("cut -c1-10 f", "取 1-10 字符")], "高", "日常"),
    c("paste", "text", "横向合并文件", ["合并列", "paste"],
      [("paste a.txt b.txt", "并排合并")], "低", "日常"),
    c("join", "text", "按字段连接", ["连接", "join"],
      [("join a.txt b.txt", "按公共字段连接")], "低", "进阶"),
    c("comm", "text", "比较已排序文件", ["比较文件", "comm"],
      [("comm a.txt b.txt", "显示交集/差集")], "低", "日常"),
    c("diff", "text", "比较文件差异", ["比较差异", "diff"],
      [("diff a.txt b.txt", "逐行比较"), ("diff -u a b > p.patch", "生成补丁")], "高", "日常"),
    c("patch", "text", "应用补丁", ["打补丁", "patch"],
      [("patch < p.patch", "应用补丁")], "中", "日常",
      "打错可能损坏文件，先 --dry-run 预览"),
    c("tr", "text", "字符转换/删除", ["字符替换", "tr"],
      [("tr 'a-z' 'A-Z'", "转大写"), ("tr -d '\r'", "删除回车符")], "中", "日常"),
    c("wc", "text", "统计行/词/字节", ["统计", "wc"],
      [("wc -l f.txt", "统计行数"), ("wc -w f", "统计词数")], "高", "入门"),
    c("split", "text", "拆分文件", ["拆分", "split"],
      [("split -l 1000 f", "每 1000 行拆分")], "低", "日常"),
    c("csplit", "text", "按上下文拆分", ["拆分", "csplit"],
      [("csplit f '/pattern/'", "按模式拆分")], "低", "进阶"),
    c("fmt", "text", "段落格式化", ["格式化", "fmt"],
      [("fmt -w 60 f", "每行 60 列")], "低", "日常"),
    c("expand", "text", "制表符转空格", ["制表符", "expand"],
      [("expand f.txt", "tab 转空格")], "低", "日常"),
    c("unexpand", "text", "空格转制表符", ["制表符", "unexpand"],
      [("unexpand -a f", "空格转 tab")], "低", "日常"),

    # ---- 文件权限与属性 ----
    c("chmod", "perm", "修改权限", ["权限", "chmod"],
      [("chmod 644 f", "所有者读写他人只读"), ("chmod +x script.sh", "加可执行")], "高", "入门",
      "误用 777 会导致全网可写，存在安全风险"),
    c("chown", "perm", "修改属主", ["属主", "chown"],
      [("sudo chown u:g f", "改用户和组"), ("chown -R u dir", "递归修改")], "高", "日常",
      "改他人文件需 sudo；递归 -R 谨慎"),
    c("chgrp", "perm", "修改属组", ["属组", "chgrp"],
      [("chgrp dev f", "改组为 dev")], "中", "日常"),
    c("umask", "perm", "设置默认权限掩码", ["默认权限", "umask"],
      [("umask 022", "新建文件默认 755/644")], "中", "日常"),
    c("chattr", "perm", "修改文件扩展属性", ["扩展属性", "chattr"],
      [("chattr +i f", "不可修改/删除（immutable）"), ("chattr +a f", "仅可追加")], "低", "进阶",
      "需 root；+i 后连 root 也删不掉，用 -i 解除"),
    c("lsattr", "perm", "查看扩展属性", ["扩展属性", "lsattr"],
      [("lsattr f", "查看 chattr 属性")], "低", "进阶"),
    c("setfacl", "perm", "设置 ACL 细粒度权限", ["ACL", "setfacl"],
      [("setfacl -m u:alice:r f", "给用户 alice 读权限")], "低", "进阶"),
    c("getfacl", "perm", "查看 ACL", ["ACL", "getfacl"],
      [("getfacl f", "查看详细 ACL")], "低", "进阶"),

    # ---- 用户与用户组 ----
    c("sudo", "user", "以其他用户（默认 root）执行", ["提权", "sudo"],
      [("sudo apt update", "以 root 执行"), ("sudo -u www cmd", "以 www 执行")], "高", "入门",
      "滥用 sudo 有风险；用 sudo -l 查看可执行的命令"),
    c("su", "user", "切换用户", ["切换用户", "su"],
      [("su -", "切换到 root 并加载环境"), ("su alice", "切到 alice")], "高", "日常", None,
      "su - 加载目标用户环境；su 不加载"),
    c("useradd", "user", "新建用户", ["新建用户", "useradd"],
      [("sudo useradd -m alice", "建用户并建家目录")], "中", "日常",
      "不加 -m 可能不建家目录；用 useradd -m -s /bin/bash"),
    c("userdel", "user", "删除用户", ["删除用户", "userdel"],
      [("sudo userdel -r alice", "删用户并清家目录")], "低", "日常",
      "-r 才会删家目录，否则残留"),
    c("usermod", "user", "修改用户", ["修改用户", "usermod"],
      [("sudo usermod -aG sudo alice", "加入 sudo 组")], "中", "日常"),
    c("groupadd", "user", "新建组", ["新建组", "groupadd"],
      [("sudo groupadd dev", "建 dev 组")], "低", "日常"),
    c("groupdel", "user", "删除组", ["删除组", "groupdel"],
      [("sudo groupdel dev", "删 dev 组")], "低", "日常"),
    c("passwd", "user", "修改密码", ["密码", "passwd"],
      [("passwd", "改自己密码"), ("sudo passwd alice", "改他人密码")], "中", "日常"),
    c("chpasswd", "user", "批量改密码", ["批量密码", "chpasswd"],
      [("echo 'alice:new' | chpasswd", "批量设置")], "低", "进阶"),
    c("newgrp", "user", "切换有效组", ["切换组", "newgrp"],
      [("newgrp dev", "临时切换有效组")], "低", "日常"),
    c("gpasswd", "user", "管理组成员", ["组成员", "gpasswd"],
      [("sudo gpasswd -a alice dev", "加用户到组")], "低", "日常"),
    c("id", "user", "显示用户/组 ID", ["用户ID", "id"],
      [("id", "看当前 uid/gid"), ("id alice", "看指定用户")], "中", "入门"),
    c("whoami", "user", "显示当前用户名", ["当前用户", "whoami"],
      [("whoami", "打印当前用户名")], "中", "入门"),
    c("who", "user", "显示登录用户", ["登录用户", "who"],
      [("who", "看谁在线")], "低", "入门"),
    c("w", "user", "显示登录用户及进程", ["登录用户", "w"],
      [("w", "看用户与正在运行的命令")], "低", "日常"),
    c("last", "user", "最近登录记录", ["登录记录", "last"],
      [("last", "查看登录历史")], "低", "日常"),
    c("lastlog", "user", "所有用户最后登录", ["最后登录", "lastlog"],
      [("lastlog", "各用户末次登录")], "低", "日常"),
    c("groups", "user", "显示用户所属组", ["所属组", "groups"],
      [("groups alice", "看 alice 的组")], "低", "入门"),
    c("visudo", "user", "安全编辑 sudoers", ["sudoers", "visudo"],
      [("sudo visudo", "编辑 sudo 配置（带语法检查）")], "低", "进阶",
      "务必用 visudo 而非直接改，避免锁死 sudo"),
    c("finger", "user", "用户信息查询", ["用户信息", "finger"],
      [("finger alice", "查看用户详情")], "低", "日常"),

    # ---- 进程管理 ----
    c("ps", "proc", "查看进程", ["进程", "ps"],
      [("ps aux", "看全部进程"), ("ps -ef | grep nginx", "查 nginx")], "高", "入门"),
    c("top", "proc", "实时进程监控", ["实时监控", "top"],
      [("top", "动态查看资源占用")], "高", "日常", None, "top 实时；htop 更友好（需安装）"),
    c("htop", "proc", "增强版进程监控", ["进程监控", "htop"],
      [("htop", "彩色可交互监控")], "中", "日常"),
    c("kill", "proc", "发送信号终止进程", ["结束进程", "kill"],
      [("kill 1234", "默认 SIGTERM"), ("kill -9 1234", "强制 SIGKILL")], "高", "日常",
      "先 SIGTERM(-15)，不行再 -9；-9 可能丢数据"),
    c("pkill", "proc", "按名结束进程", ["按名结束", "pkill"],
      [("pkill nginx", "结束所有 nginx")], "中", "日常",
      "误杀同名进程，先 pkill -l 预览"),
    c("killall", "proc", "按名结束全部", ["按名结束", "killall"],
      [("killall python", "结束所有 python")], "中", "日常"),
    c("pgrep", "proc", "按名查找 PID", ["查找PID", "pgrep"],
      [("pgrep nginx", "找 nginx 的 PID")], "中", "日常"),
    c("pidof", "proc", "查进程 PID", ["PID", "pidof"],
      [("pidof nginx", "返回 nginx PID")], "低", "日常"),
    c("jobs", "proc", "查看后台任务", ["后台任务", "jobs"],
      [("jobs", "列出当前 shell 的后台任务")], "中", "日常"),
    c("bg", "proc", "任务转后台", ["后台", "bg"],
      [("bg %1", "把任务 1 放后台")], "中", "日常"),
    c("fg", "proc", "任务转前台", ["前台", "fg"],
      [("fg %1", "把任务 1 调回前台")], "中", "日常"),
    c("nohup", "proc", "退出后继续运行", ["后台运行", "nohup"],
      [("nohup cmd &", "断开终端仍运行")], "中", "日常"),
    c("disown", "proc", "脱离 shell 作业", ["脱离作业", "disown"],
      [("disown", "移除作业防 HUP 信号")], "低", "进阶"),
    c("nice", "proc", "调整优先级启动", ["优先级", "nice"],
      [("nice -n 10 cmd", "低优先级运行")], "低", "进阶"),
    c("renice", "proc", "调整运行中优先级", ["优先级", "renice"],
      [("renice -n 5 -p 1234", "改 PID 优先级")], "低", "进阶"),
    c("at", "proc", "定时一次性任务", ["定时任务", "at"],
      [("echo 'cmd' | at 18:00", "18 点执行")], "低", "日常"),
    c("batch", "proc", "系统空闲时执行", ["空闲执行", "batch"],
      [("batch", "负载低时运行")], "低", "日常"),
    c("crontab", "proc", "周期性任务", ["定时任务", "crontab"],
      [("crontab -e", "编辑计划任务"), ("crontab -l", "列出任务")], "中", "日常",
      "格式 分 时 日 月 周；注意环境变量可能缺失"),
    c("runlevel", "proc", "查看运行级别", ["运行级别", "runlevel"],
      [("runlevel", "显示当前/上一级别")], "低", "日常"),
    c("init", "proc", "切换运行级别", ["运行级别", "init"],
      [("sudo init 0", "关机（旧式）")], "低", "日常"),
    c("watch", "proc", "周期执行并刷新", ["周期执行", "watch"],
      [("watch -n 1 'ls -l'", "每秒刷新")], "中", "日常"),
    c("lsof", "proc", "列出打开的文件/端口", ["打开文件", "端口", "lsof"],
      [("lsof -i :80", "看 80 端口占用"), ("lsof /var/log", "谁在写该文件")], "中", "进阶"),
    c("strace", "proc", "跟踪系统调用", ["系统调用", "strace"],
      [("strace -p 1234", "跟踪进程系统调用")], "低", "进阶"),
    c("time", "proc", "统计命令耗时", ["耗时", "time"],
      [("time ./build.sh", "测运行时间")], "中", "日常"),
    c("timeout", "proc", "限时运行命令", ["超时", "timeout"],
      [("timeout 10 cmd", "10 秒后终止")], "低", "日常"),

    # ---- 磁盘与文件系统 ----
    c("df", "disk", "查看磁盘空间", ["磁盘空间", "df"],
      [("df -h", "人类可读显示各分区")], "高", "入门"),
    c("du", "disk", "查看目录/文件大小", ["目录大小", "du"],
      [("du -sh *", "当前各子项总大小"), ("du -h --max-depth=1", "一层深度")], "高", "入门",
      "du 统计文件实际占用；df 看分区整体"),
    c("mount", "disk", "挂载文件系统", ["挂载", "mount"],
      [("sudo mount /dev/sdb1 /mnt", "挂载到 /mnt")], "中", "日常", None, "mount 挂载；umount 卸载"),
    c("umount", "disk", "卸载文件系统", ["卸载", "umount"],
      [("sudo umount /mnt", "卸载")], "中", "日常",
      "设备忙时无法卸载，先关闭占用进程"),
    c("fdisk", "disk", "磁盘分区工具", ["分区", "fdisk"],
      [("sudo fdisk /dev/sdb", "交互式分区")], "低", "进阶",
      "操作分区有数据丢失风险"),
    c("parted", "disk", "分区工具（支持 GPT）", ["分区", "parted"],
      [("sudo parted /dev/sdb", "分区（支持大盘）")], "低", "进阶"),
    c("lsblk", "disk", "列出块设备", ["块设备", "lsblk"],
      [("lsblk", "树状显示磁盘与分区")], "中", "日常"),
    c("blkid", "disk", "查看设备 UUID/类型", ["设备UUID", "blkid"],
      [("sudo blkid", "显示设备 UUID/文件系统")], "低", "日常"),
    c("mkfs", "disk", "格式化文件系统", ["格式化", "mkfs"],
      [("sudo mkfs.ext4 /dev/sdb1", "格式化为 ext4")], "低", "进阶",
      "格式化会清空数据！"),
    c("dd", "disk", "按块复制（磁盘镜像）", ["块复制", "dd"],
      [("dd if=in of=out bs=4M", "克隆/备份"), ("dd if=/dev/zero of=disk.img", "造镜像")], "低", "进阶",
      "if=/dev/sda 写错 of= 会毁盘，务必核对"),
    c("fsck", "disk", "检查修复文件系统", ["文件系统检查", "fsck"],
      [("sudo fsck /dev/sdb1", "检查并修复")], "低", "进阶",
      "需在卸载状态下运行"),
    c("e2fsck", "disk", "ext 文件系统检查", ["ext检查", "e2fsck"],
      [("sudo e2fsck -f /dev/sdb1", "强制检查")], "低", "进阶"),
    c("tune2fs", "disk", "调整 ext 文件系统参数", ["ext参数", "tune2fs"],
      [("sudo tune2fs -l /dev/sdb1", "查看参数")], "低", "进阶"),
    c("badblocks", "disk", "检测坏块", ["坏块", "badblocks"],
      [("sudo badblocks -v /dev/sdb", "扫描坏块")], "低", "进阶"),
    c("nvme", "disk", "NVMe 固态管理", ["nvme", "nvme"],
      [("sudo nvme list", "列出 nvme 设备")], "低", "进阶"),
    c("losetup", "disk", "管理回环设备", ["回环设备", "losetup"],
      [("sudo losetup -f disk.img", "挂载镜像为设备")], "低", "进阶"),
    c("sync", "disk", "刷新缓存到磁盘", ["同步", "sync"],
      [("sync", "强制写入磁盘（卸载前用）")], "低", "日常"),
    c("mkswap", "disk", "创建交换分区", ["交换分区", "mkswap"],
      [("sudo mkswap /dev/sdb2", "建 swap")], "低", "进阶"),
    c("swapon", "disk", "启用交换", ["启用swap", "swapon"],
      [("sudo swapon /dev/sdb2", "启用 swap")], "低", "进阶"),
    c("swapoff", "disk", "关闭交换", ["关闭swap", "swapoff"],
      [("sudo swapoff /dev/sdb2", "关闭")], "低", "进阶"),
    c("dumpe2fs", "disk", "导出 ext 超级块信息", ["ext信息", "dumpe2fs"],
      [("sudo dumpe2fs /dev/sdb1", "看超级块")], "低", "进阶"),

    # ---- 网络 ----
    c("ping", "net", "测试网络连通", ["连通测试", "ping"],
      [("ping -c 4 example.com", "发 4 个包")], "高", "入门"),
    c("curl", "net", "传输 URL 数据", ["下载", "HTTP", "curl"],
      [("curl -O url", "下载保存"), ("curl -fsSL url | sh", "下载并执行")], "高", "日常",
      "管道执行下载脚本前先确认来源可信"),
    c("wget", "net", "下载文件", ["下载", "wget"],
      [("wget url", "下载到当前目录"), ("wget -c url", "断点续传")], "高", "日常"),
    c("ssh", "net", "远程安全登录", ["远程登录", "ssh"],
      [("ssh user@host", "登录远程"), ("ssh -p 2222 user@host", "指定端口")], "高", "日常"),
    c("scp", "net", "安全复制文件", ["远程复制", "scp"],
      [("scp f.txt user@host:/tmp", "上传"), ("scp -r dir user@host:~/", "递归上传")], "高", "日常"),
    c("sftp", "net", "交互式安全传输", ["安全传输", "sftp"],
      [("sftp user@host", "交互传文件")], "中", "日常"),
    c("rsync", "net", "增量同步", ["增量同步", "rsync"],
      [("rsync -avz src/ host:/dst", "远程增量备份"), ("rsync -a --delete src/ dst/", "镜像同步")], "高", "进阶",
      "--delete 会删目标多余文件，先 --dry-run"),
    c("netstat", "net", "网络状态（旧）", ["网络状态", "netstat"],
      [("netstat -tunlp", "看监听端口")], "中", "日常", None, "netstat 已过时，推荐 ss"),
    c("ss", "net", "查看套接字（新）", ["套接字", "ss"],
      [("ss -tunlp", "看监听端口（替代 netstat）")], "中", "日常", None, "ss 比 netstat 更快更全"),
    c("ip", "net", "网络配置（新）", ["网络配置", "ip"],
      [("ip addr", "看网卡 IP"), ("ip route", "看路由表")], "中", "日常", None, "ip 取代 ifconfig/route"),
    c("ifconfig", "net", "网络接口配置（旧）", ["网卡配置", "ifconfig"],
      [("ifconfig", "看接口信息")], "中", "入门", None, "已被 ip 命令取代"),
    c("traceroute", "net", "路由追踪", ["路由追踪", "traceroute"],
      [("traceroute example.com", "显示路径跳数")], "中", "日常"),
    c("mtr", "net", "路由实时诊断", ["路由诊断", "mtr"],
      [("mtr example.com", "持续监控路径")], "低", "日常"),
    c("dig", "net", "DNS 查询", ["DNS查询", "dig"],
      [("dig example.com", "查 A 记录"), ("dig @8.8.8.8 example.com", "指定 DNS")], "中", "进阶"),
    c("host", "net", "简易 DNS 查询", ["DNS查询", "host"],
      [("host example.com", "解析域名")], "低", "日常", None, "host 简单；dig 更详细"),
    c("whois", "net", "域名/IP 注册信息", ["whois", "whois"],
      [("whois example.com", "查注册信息")], "低", "日常"),
    c("nc", "net", "网络瑞士军刀", ["网络工具", "nc"],
      [("nc -l 1234", "监听端口"), ("nc host 1234 < f", "传文件")], "低", "进阶"),
    c("nmap", "net", "端口扫描", ["端口扫描", "nmap"],
      [("nmap -sV host", "扫描服务版本")], "低", "进阶",
      "扫描他人系统可能违法，仅用于自有资产"),
    c("tcpdump", "net", "抓包分析", ["抓包", "tcpdump"],
      [("sudo tcpdump -i eth0 port 80", "抓 80 端口")], "低", "进阶"),
    c("iptables", "net", "防火墙规则", ["防火墙", "iptables"],
      [("sudo iptables -L", "列出规则"), ("sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT", "放行 22")], "低", "进阶",
      "规则改动可能导致断连，谨慎；新系统多用 nftables/ufw"),
    c("ufw", "net", "简易防火墙", ["防火墙", "ufw"],
      [("sudo ufw enable", "启用"), ("sudo ufw allow 22", "放行 22")], "低", "日常", None, "ufw 是 iptables 的友好封装"),
    c("arp", "net", "查看 ARP 表", ["ARP", "arp"],
      [("arp -n", "看 IP-MAC 映射")], "低", "日常"),
    c("socat", "net", "多协议中继", ["中继", "socat"],
      [("socat TCP-LISTEN:1234,fork TCP:host:80", "端口转发")], "低", "进阶"),
    c("nslookup", "net", "DNS 查询（旧）", ["DNS查询", "nslookup"],
      [("nslookup example.com", "查解析")], "低", "入门", None, "已被 dig/host 取代"),

    # ---- 压缩与归档 ----
    c("tar", "archive", "打包/解包", ["打包", "tar"],
      [("tar -czf a.tar.gz dir/", "打包并 gzip"), ("tar -xzf a.tar.gz -C /tmp", "解压到 /tmp")], "高", "入门",
      "顺序敏感：f 后紧跟文件名；解压先看内容 tar -tzf"),
    c("gzip", "archive", "gzip 压缩", ["压缩", "gzip"],
      [("gzip f.txt", "压缩为 f.txt.gz（删原文件）"), ("gzip -k f.txt", "保留原文件")], "高", "日常",
      "默认删除源文件，保留用 -k 或 gzip -c > "),
    c("gunzip", "archive", "解压 gzip", ["解压", "gunzip"],
      [("gunzip f.gz", "解压")], "低", "日常", None, "gunzip 即 gzip -d"),
    c("bzip2", "archive", "bzip2 压缩", ["压缩", "bzip2"],
      [("bzip2 f.txt", "更高压缩率更慢")], "低", "日常"),
    c("xz", "archive", "xz 压缩", ["压缩", "xz"],
      [("xz -9 f.txt", "极高压缩率")], "低", "日常"),
    c("zip", "archive", "打包为 zip", ["zip", "zip"],
      [("zip -r a.zip dir/", "递归打包")], "中", "日常"),
    c("unzip", "archive", "解压 zip", ["解压zip", "unzip"],
      [("unzip a.zip -d out/", "解压到 out")], "中", "日常"),
    c("7z", "archive", "7-Zip 压缩", ["7z", "7z"],
      [("7z a a.7z dir/", "压缩"), ("7z x a.7z", "解压")], "低", "日常"),
    c("zstd", "archive", "Zstandard 压缩", ["zstd", "zstd"],
      [("zstd f.txt", "快速高压缩")], "低", "日常"),
    c("lz4", "archive", "lz4 快速压缩", ["lz4", "lz4"],
      [("lz4 f.txt", "极快压缩")], "低", "日常"),
    c("compress", "archive", "老式压缩", ["压缩", "compress"],
      [("compress f", "生成 .f.Z")], "低", "日常"),
    c("unrar", "archive", "解压 rar", ["解压rar", "unrar"],
      [("unrar x a.rar", "解压 rar")], "低", "日常"),
    c("rar", "archive", "创建 rar", ["rar", "rar"],
      [("rar a a.rar dir/", "打包为 rar（需安装）")], "低", "日常"),
    c("zcat", "archive", "查看 gzip 内容", ["查看压缩", "zcat"],
      [("zcat f.gz", "不解压直接看")], "低", "日常", None, "zcat 即 gzip -dc"),

    # ---- 系统信息与监控 ----
    c("uname", "sys", "系统内核信息", ["内核信息", "uname"],
      [("uname -a", "全部系统信息")], "中", "入门"),
    c("uptime", "sys", "运行时长与负载", ["运行时长", "uptime"],
      [("uptime", "看运行时间与负载")], "中", "入门"),
    c("free", "sys", "内存使用", ["内存", "free"],
      [("free -h", "人类可读内存")], "高", "入门"),
    c("lscpu", "sys", "CPU 信息", ["CPU信息", "lscpu"],
      [("lscpu", "看 CPU 架构/核数")], "中", "日常"),
    c("lsmem", "sys", "内存拓扑", ["内存", "lsmem"],
      [("lsmem", "看内存块布局")], "低", "日常"),
    c("lsusb", "sys", "USB 设备列表", ["USB", "lsusb"],
      [("lsusb", "列出 USB 设备")], "低", "日常"),
    c("lspci", "sys", "PCI 设备列表", ["PCI", "lspci"],
      [("lspci", "列出 PCI 设备")], "低", "日常"),
    c("lshw", "sys", "硬件详情", ["硬件", "lshw"],
      [("sudo lshw", "完整硬件信息")], "低", "进阶"),
    c("dmidecode", "sys", "DMI/BIOS 信息", ["硬件", "dmidecode"],
      [("sudo dmidecode -t memory", "内存信息")], "低", "进阶"),
    c("dmesg", "sys", "内核环形缓冲", ["内核日志", "dmesg"],
      [("dmesg | tail", "看最近内核消息"), ("sudo dmesg -w", "实时")], "中", "进阶"),
    c("journalctl", "sys", "systemd 日志", ["系统日志", "journalctl"],
      [("journalctl -xe", "看错误日志"), ("journalctl -u nginx", "某服务日志")], "中", "日常"),
    c("hostnamectl", "sys", "主机名管理", ["主机名", "hostnamectl"],
      [("hostnamectl", "查看/设置主机名")], "低", "日常"),
    c("timedatectl", "sys", "时间日期管理", ["时间", "timedatectl"],
      [("timedatectl", "看时钟与 NTP")], "低", "日常"),
    c("localectl", "sys", "本地化设置", ["本地化", "localectl"],
      [("localectl", "看语言/键盘设置")], "低", "日常"),
    c("loginctl", "sys", "登录会话管理", ["会话", "loginctl"],
      [("loginctl", "查看登录会话")], "低", "日常"),
    c("iostat", "sys", "CPU/IO 统计", ["IO统计", "iostat"],
      [("iostat -x 1", "每秒扩展 IO 统计")], "低", "进阶"),
    c("vmstat", "sys", "虚拟内存统计", ["内存统计", "vmstat"],
      [("vmstat 1", "每秒系统统计")], "低", "进阶"),
    c("sar", "sys", "系统活动报告", ["系统报告", "sar"],
      [("sar -u 1 3", "CPU 使用率采样")], "低", "进阶"),
    c("mpstat", "sys", "CPU 核心统计", ["CPU统计", "mpstat"],
      [("mpstat -P ALL 1", "每核使用率")], "低", "进阶"),
    c("nproc", "sys", "CPU 核心数", ["核心数", "nproc"],
      [("nproc", "输出逻辑核心数")], "低", "入门"),
    c("sensors", "sys", "温度监控", ["温度", "sensors"],
      [("sensors", "看 CPU/主板温度")], "低", "日常"),

    # ---- 关机与系统控制 ----
    c("shutdown", "power", "关机/重启", ["关机", "shutdown"],
      [("sudo shutdown -h now", "立即关机"), ("sudo shutdown -r 20:00", "20 点重启")], "中", "入门",
      "远程机器慎用，确认不会断错"),
    c("reboot", "power", "重启", ["重启", "reboot"],
      [("sudo reboot", "立即重启")], "中", "入门"),
    c("poweroff", "power", "关机", ["关机", "poweroff"],
      [("sudo poweroff", "立即关机")], "中", "入门"),
    c("halt", "power", "停止系统", ["停机", "halt"],
      [("sudo halt", "停止 CPU（需断电）")], "低", "入门"),
    c("systemctl", "power", "systemd 服务管理", ["服务管理", "systemctl"],
      [("sudo systemctl restart nginx", "重启服务"), ("systemctl status nginx", "看状态"), ("systemctl enable nginx", "开机自启")], "高", "日常",
      "enable 才开机自启；改配置后 daemon-reload"),
    c("telinit", "power", "切换运行级别（旧）", ["运行级别", "telinit"],
      [("sudo telinit 3", "切到多用户")], "低", "日常", None, "现代多用 systemctl 的 target"),

    # ---- 软件包管理 ----
    c("apt", "pkg", "Debian 系包管理（新）", ["包管理", "apt"],
      [("sudo apt update", "更新索引"), ("sudo apt install -y nginx", "安装"), ("sudo apt remove nginx", "卸载")], "高", "入门"),
    c("apt-get", "pkg", "底层 apt（脚本用）", ["包管理", "apt-get"],
      [("sudo apt-get update", "更新索引")], "中", "入门", None, "交互/脚本推荐 apt；apt-get 兼容旧脚本"),
    c("dpkg", "pkg", "Debian 底层包操作", ["包管理", "dpkg"],
      [("sudo dpkg -i pkg.deb", "装本地 deb"), ("dpkg -l", "列出已装包")], "中", "日常", None, "dpkg 不解决依赖；apt 会"),
    c("yum", "pkg", "RHEL 旧包管理", ["包管理", "yum"],
      [("sudo yum install nginx", "安装")], "低", "日常"),
    c("dnf", "pkg", "RHEL 新包管理", ["包管理", "dnf"],
      [("sudo dnf install nginx", "安装")], "低", "日常", None, "dnf 取代 yum"),
    c("rpm", "pkg", "RHEL 底层包管理", ["包管理", "rpm"],
      [("rpm -qa", "列出已装包"), ("sudo rpm -ivh pkg.rpm", "装 rpm")], "低", "日常"),
    c("pacman", "pkg", "Arch 包管理", ["包管理", "pacman"],
      [("sudo pacman -Syu", "更新系统"), ("sudo pacman -S pkg", "安装")], "低", "日常"),
    c("zypper", "pkg", "openSUSE 包管理", ["包管理", "zypper"],
      [("sudo zypper install pkg", "安装")], "低", "日常"),
    c("apk", "pkg", "Alpine 包管理", ["包管理", "apk"],
      [("apk add pkg", "安装（容器常用）")], "低", "日常"),
    c("snap", "pkg", "通用快照包", ["snap", "snap"],
      [("sudo snap install code", "安装")], "低", "日常"),
    c("flatpak", "pkg", "沙盒应用", ["flatpak", "flatpak"],
      [("flatpak install app", "安装")], "低", "日常"),
    c("brew", "pkg", "macOS/Homebrew", ["brew", "brew"],
      [("brew install wget", "macOS 装包")], "低", "日常"),
    c("apt-cache", "pkg", "查询包信息", ["包查询", "apt-cache"],
      [("apt-cache search nginx", "搜索包")], "低", "日常"),

    # ---- 内核模块 ----
    c("lsmod", "kernel", "列出已加载模块", ["内核模块", "lsmod"],
      [("lsmod", "看已加载模块")], "低", "日常"),
    c("modprobe", "kernel", "加载/卸载模块", ["模块加载", "modprobe"],
      [("sudo modprobe kvm", "加载模块"), ("sudo modprobe -r kvm", "卸载")], "低", "进阶",
      "修改需谨慎，错误模块可致系统不稳"),
    c("insmod", "kernel", "插入模块文件", ["模块插入", "insmod"],
      [("sudo insmod drv.ko", "加载指定 .ko")], "低", "进阶", None, "insmod 不自动解决依赖；modprobe 会"),
    c("rmmod", "kernel", "移除模块", ["模块移除", "rmmod"],
      [("sudo rmmod drv", "移除模块")], "低", "进阶"),
    c("depmod", "kernel", "生成模块依赖", ["模块依赖", "depmod"],
      [("sudo depmod", "更新依赖映射")], "低", "进阶"),
    c("modinfo", "kernel", "查看模块信息", ["模块信息", "modinfo"],
      [("modinfo kvm", "看模块详情/参数")], "低", "日常"),

    # ---- Shell 内建命令 ----
    c("echo", "shell", "输出文本", ["输出", "echo"],
      [("echo hello", "打印文本"), ("echo $PATH", "打印变量")], "高", "入门"),
    c("printf", "shell", "格式化输出", ["格式化输出", "printf"],
      [("printf '%s\n' a b", "格式输出")], "中", "日常", None, "printf 更可控；echo 简单"),
    c("export", "shell", "导出环境变量", ["环境变量", "export"],
      [("export PATH=$PATH:/opt/bin", "追加 PATH")], "高", "日常"),
    c("alias", "shell", "设置命令别名", ["别名", "alias"],
      [("alias ll='ls -la'", "设别名")], "中", "日常"),
    c("unalias", "shell", "取消别名", ["取消别名", "unalias"],
      [("unalias ll", "删除别名")], "低", "日常"),
    c("source", "shell", "当前 shell 执行脚本", ["执行脚本", "source"],
      [("source ~/.bashrc", "重载配置")], "高", "日常", None, "source 在当前 shell 执行；./script 在子 shell"),
    c("history", "shell", "命令历史", ["历史", "history"],
      [("history", "列出历史"), ("!123", "执行第 123 条")], "中", "入门"),
    c("read", "shell", "读取输入", ["读取输入", "read"],
      [("read name", "读入变量")], "低", "进阶"),
    c("eval", "shell", "执行字符串命令", ["执行字符串", "eval"],
      [("eval \"$cmd\"", "动态执行")], "低", "进阶",
      "拼接用户输入执行有注入风险"),
    c("exec", "shell", "替换当前进程", ["替换进程", "exec"],
      [("exec bash", "替换当前 shell")], "低", "进阶"),
    c("trap", "shell", "捕获信号", ["信号捕获", "trap"],
      [("trap 'clean' EXIT", "退出时清理")], "低", "进阶"),
    c("set", "shell", "设置 shell 选项", ["shell选项", "set"],
      [("set -e", "遇错即停"), ("set -x", "打印执行命令")], "低", "进阶"),
    c("unset", "shell", "删除变量/函数", ["删除变量", "unset"],
      [("unset VAR", "删除变量")], "低", "日常"),
    c("shopt", "shell", "shell 行为选项", ["shell选项", "shopt"],
      [("shopt -s globstar", "启用 ** 递归匹配")], "低", "进阶"),
    c("type", "shell", "显示命令类型", ["命令类型", "type"],
      [("type ls", "显示是别名/内建/文件")], "中", "日常"),
    c("command", "shell", "绕过别名执行", ["绕过别名", "command"],
      [("command ls", "忽略 ls 别名")], "低", "日常"),
    c("builtin", "shell", "调用内建", ["内建", "builtin"],
      [("builtin cd", "强制用内建 cd")], "低", "进阶"),
    c("let", "shell", "算术运算", ["算术", "let"],
      [("let x=x+1", "整数运算")], "低", "进阶"),
    c("wait", "shell", "等待后台作业", ["等待", "wait"],
      [("wait %1", "等任务完成")], "低", "进阶"),
    c("ulimit", "shell", "资源限制", ["资源限制", "ulimit"],
      [("ulimit -n 65535", "提高打开文件数上限")], "低", "进阶"),
    c("test", "shell", "条件测试", ["条件测试", "test"],
      [("test -f f.txt", "判断文件存在")], "低", "进阶", None, "test 即 [ ... ]"),
    c("fc", "shell", "编辑/重放历史", ["历史", "fc"],
      [("fc", "编辑上条命令")], "低", "进阶"),
    c("[", "shell", "条件测试内建", ["条件测试", "["],
      [("[ -d dir ]", "判断目录存在")], "低", "进阶", None, "[ 是 test 的同名内建，注意收尾 ]"),

    # ---- 编辑器与工具 ----
    c("vi", "editor", "经典编辑器", ["编辑器", "vi"],
      [("vi f.txt", "打开文件")], "中", "入门"),
    c("vim", "editor", "增强 vi", ["编辑器", "vim"],
      [("vim f.txt", "打开（更强）")], "中", "日常", None, "vim 是 vi 的增强版"),
    c("nano", "editor", "简易编辑器", ["编辑器", "nano"],
      [("nano f.txt", "新手友好编辑")], "中", "入门"),
    c("emacs", "editor", "Emacs 编辑器", ["编辑器", "emacs"],
      [("emacs f.txt", "打开")], "低", "日常"),
    c("ed", "editor", "行编辑器", ["行编辑器", "ed"],
      [("ed f.txt", "行编辑")], "低", "进阶"),
    c("man", "editor", "查看手册", ["手册", "man"],
      [("man ls", "看 ls 手册"), ("man -k keyword", "按关键词搜手册")], "高", "入门"),
    c("info", "editor", "GNU 信息文档", ["文档", "info"],
      [("info coreutils", "看 GNU 文档")], "低", "日常"),
    c("which", "editor", "显示命令路径", ["命令路径", "which"],
      [("which python", "看 python 位置")], "高", "入门"),
    c("whereis", "editor", "定位命令/源码/手册", ["定位", "whereis"],
      [("whereis ls", "找 ls 相关文件")], "低", "日常"),
    c("whatis", "editor", "一行命令描述", ["描述", "whatis"],
      [("whatis ls", "看简介")], "低", "入门"),
    c("locate", "editor", "快速文件搜索（数据库）", ["文件搜索", "locate"],
      [("locate nginx.conf", "从数据库搜")], "中", "日常",
      "依赖 updatedb；新文件可能搜不到"),
    c("updatedb", "editor", "更新搜索数据库", ["更新数据库", "updatedb"],
      [("sudo updatedb", "重建 locate 索引")], "低", "日常"),
    c("date", "editor", "显示/设置日期", ["日期", "date"],
      [("date", "当前时间"), ("date +%Y%m%d", "格式化")], "中", "入门"),
    c("cal", "editor", "显示日历", ["日历", "cal"],
      [("cal", "当月日历"), ("cal 2026", "全年")], "低", "入门"),
    c("sleep", "editor", "暂停指定秒数", ["暂停", "sleep"],
      [("sleep 5", "等 5 秒")], "中", "日常"),
    c("yes", "editor", "持续输出", ["持续输出", "yes"],
      [("yes | cmd", "自动确认")], "低", "日常"),
    c("clear", "editor", "清屏", ["清屏", "clear"],
      [("clear", "清屏")], "中", "入门"),
    c("script", "editor", "记录终端会话", ["记录会话", "script"],
      [("script session.log", "记录全部输出")], "低", "日常"),
    c("wall", "editor", "向所有终端发消息", ["广播", "wall"],
      [("wall '维护通知'", "群发消息")], "低", "日常"),
    c("mesg", "editor", "控制消息接收", ["消息", "mesg"],
      [("mesg n", "拒收 wall 消息")], "低", "日常"),
]

GIT = [
    # ---- 仓库与配置 ----
    c("git init", "g_config", "初始化仓库", ["初始化", "仓库", "git init"],
      [("git init", "当前目录建仓库"), ("git init --bare", "建裸仓库（服务端）")], "高", "入门"),
    c("git clone", "g_config", "克隆仓库", ["克隆", "git clone"],
      [("git clone url", "克隆到同名目录"), ("git clone -b dev url", "克隆指定分支")], "高", "入门"),
    c("git config", "g_config", "配置", ["配置", "git config"],
      [("git config --global user.name 'x'", "设用户名"), ("git config --list", "查看配置")], "高", "入门"),
    c("git help", "g_config", "查看帮助", ["帮助", "git help"],
      [("git help commit", "看 commit 手册")], "中", "入门"),
    c("git var", "g_config", "显示 git 变量", ["变量", "git var"],
      [("git var GIT_AUTHOR_IDENT", "看作者身份")], "低", "进阶"),
    c("git version", "g_config", "显示版本", ["版本", "git version"],
      [("git version", "查看 git 版本")], "低", "入门"),
    c("git bugreport", "g_config", "生成缺陷报告", ["缺陷报告", "git bugreport"],
      [("git bugreport", "生成环境报告")], "低", "日常"),

    # ---- 暂存与提交 ----
    c("git status", "g_commit", "查看状态", ["状态", "git status"],
      [("git status", "看改动"), ("git status -s", "紧凑状态")], "高", "入门"),
    c("git add", "g_commit", "暂存改动", ["暂存", "git add"],
      [("git add .", "暂存全部"), ("git add -p", "交互暂存")], "高", "入门",
      "add . 会暂存所有，含敏感文件，注意 .gitignore"),
    c("git commit", "g_commit", "提交", ["提交", "git commit"],
      [("git commit -m 'msg'", "提交"), ("git commit --amend", "修改上次提交")], "高", "入门"),
    c("git rm", "g_commit", "删除并暂存", ["删除", "git rm"],
      [("git rm f.txt", "删文件并暂存")], "中", "入门"),
    c("git mv", "g_commit", "移动/重命名并暂存", ["移动", "git mv"],
      [("git mv a.txt b.txt", "重命名")], "中", "入门"),
    c("git clean", "g_commit", "删除未跟踪文件", ["清理", "git clean"],
      [("git clean -fd", "删未跟踪文件/目录"), ("git clean -n", "预览")], "中", "日常",
      "-fd 不可恢复，先 -n 预览"),
    c("git stage", "g_commit", "add 别名", ["暂存", "git stage"],
      [("git stage .", "同 add")], "低", "日常", None, "git stage 是 git add 的别名"),

    # ---- 查看与比较 ----
    c("git log", "g_view", "查看提交历史", ["历史", "git log"],
      [("git log", "默认历史"), ("git log --oneline --graph --all", "图形化")], "高", "入门"),
    c("git show", "g_view", "显示对象内容", ["显示", "git show"],
      [("git show", "看最近提交"), ("git show <sha>", "看某提交")], "高", "日常"),
    c("git diff", "g_view", "查看差异", ["差异", "git diff"],
      [("git diff", "工作区 vs 暂存"), ("git diff --staged", "暂存 vs 上次提交")], "高", "入门"),
    c("git blame", "g_view", "逐行标注作者", ["溯源", "git blame"],
      [("git blame f.txt", "看每行作者")], "中", "日常"),
    c("git grep", "g_view", "仓库内搜索", ["搜索", "git grep"],
      [("git grep 'func'", "在版本库搜")], "中", "日常"),
    c("git shortlog", "g_view", "按作者汇总提交", ["汇总", "git shortlog"],
      [("git shortlog -sn", "各作者提交数")], "低", "日常"),
    c("git describe", "g_view", "用标签描述提交", ["描述", "git describe"],
      [("git describe --tags", "最近标签+偏移")], "低", "日常"),
    c("git reflog", "g_view", "引用日志（含丢失提交）", ["引用日志", "git reflog"],
      [("git reflog", "看 HEAD 变动历史")], "中", "进阶",
      "误删提交可用 reflog 找回"),
    c("git whatchanged", "g_view", "显示提交改动文件", ["改动", "git whatchanged"],
      [("git whatchanged -p", "类 log 加补丁")], "低", "日常", None, "类似 git log 但侧重文件列表"),

    # ---- 分支与合并 ----
    c("git branch", "g_branch", "分支管理", ["分支", "git branch"],
      [("git branch", "列分支"), ("git branch -d feat", "删已合并分支")], "高", "入门"),
    c("git switch", "g_branch", "切换/新建分支", ["切换分支", "git switch"],
      [("git switch main", "切换"), ("git switch -c feat", "新建并切换")], "高", "日常", None,
      "switch 专用于分支（2.23+），比 checkout 清晰"),
    c("git checkout", "g_branch", "切换分支/恢复文件", ["检出", "撤销改动", "git checkout"],
      [("git checkout main", "切分支"), ("git checkout -- f.txt", "丢弃改动")], "高", "日常",
      "checkout -- 丢弃改动不可恢复；切分支用 switch 更安全"),
    c("git merge", "g_branch", "合并分支", ["合并", "git merge"],
      [("git merge feat", "合并 feat 到当前"), ("git merge --no-ff feat", "保留合并点")], "高", "日常"),
    c("git mergetool", "g_branch", "图形化解决冲突", ["解决冲突", "git mergetool"],
      [("git mergetool", "启动合并工具")], "中", "进阶"),
    c("git rebase", "g_branch", "变基", ["变基", "git rebase"],
      [("git rebase main", "把当前变基到 main"), ("git rebase -i HEAD~3", "交互整理")], "中", "进阶",
      "已推送的提交勿 rebase，会改写历史"),
    c("git cherry-pick", "g_branch", "复制某次提交", ["遴选", "git cherry-pick"],
      [("git cherry-pick <sha>", "复制到当前分支")], "中", "进阶"),
    c("git tag", "g_branch", "打标签", ["标签", "git tag"],
      [("git tag v1.0", "轻量标签"), ("git tag -a v1.0 -m 'rel'", "附注标签")], "中", "日常"),
    c("git range-diff", "g_branch", "比较两个提交区间", ["区间差异", "git range-diff"],
      [("git range-diff A..B C..D", "比较两区间")], "低", "进阶"),

    # ---- 远程协作 ----
    c("git remote", "g_remote", "远程仓库管理", ["远程", "git remote"],
      [("git remote add origin url", "加远程"), ("git remote -v", "看远程")], "高", "入门"),
    c("git fetch", "g_remote", "拉取但不合并", ["拉取", "git fetch"],
      [("git fetch origin", "取远端更新"), ("git fetch -p", "删过时远程分支")], "高", "日常"),
    c("git pull", "g_remote", "拉取并合并", ["拉取合并", "git pull"],
      [("git pull", "拉取并合并"), ("git pull --rebase", "变基式拉取")], "高", "日常",
      "pull 等价于 fetch+merge；用 --rebase 减少合并提交"),
    c("git push", "g_remote", "推送", ["推送", "git push"],
      [("git push -u origin main", "首次推送并关联"), ("git push --force-with-lease", "安全强推")], "高", "日常",
      "已推送的历史勿强推；必须时用 --force-with-lease"),
    c("git submodule", "g_remote", "子模块", ["子模块", "git submodule"],
      [("git submodule add url lib", "加子模块"), ("git submodule update --init", "初始化")], "低", "进阶"),
    c("git worktree", "g_remote", "多工作树", ["工作树", "git worktree"],
      [("git worktree add ../wt main", "另开一个分支目录")], "低", "进阶"),
    c("git bundle", "g_remote", "打包为单文件", ["打包", "git bundle"],
      [("git bundle create r.bundle --all", "离线传输用")], "低", "进阶"),
    c("git request-pull", "g_remote", "生成拉取请求说明", ["拉取请求", "git request-pull"],
      [("git request-pull base origin", "生成说明")], "低", "日常"),

    # ---- 撤销与重置 ----
    c("git reset", "g_undo", "重置", ["重置", "撤销提交", "git reset"],
      [("git reset --soft HEAD~1", "撤提交留改动"), ("git reset --hard HEAD~1", "彻底丢弃")], "高", "日常",
      "--hard 丢弃工作区改动，不可恢复；优先 --soft/--mixed"),
    c("git restore", "g_undo", "恢复工作区/暂存", ["恢复", "撤销改动", "git restore"],
      [("git restore --staged f", "移出暂存"), ("git restore f", "丢弃工作区改动")], "高", "日常", None,
      "restore 专用于恢复（2.23+），语义清晰"),
    c("git revert", "g_undo", "反向提交", ["撤销", "撤销提交", "git revert"],
      [("git revert <sha>", "生成抵消提交")], "中", "日常", None,
      "revert 不改历史，适合已推送；reset 改历史"),
    c("git stash", "g_undo", "暂存快照", ["暂存快照", "git stash"],
      [("git stash push -m 'wip'", "暂存"), ("git stash pop", "恢复并删除")], "中", "日常"),

    # ---- 补丁与邮件 ----
    c("git format-patch", "g_patch", "生成补丁邮件", ["生成补丁", "git format-patch"],
      [("git format-patch origin/main", "生成一系列 .patch")], "低", "进阶"),
    c("git am", "g_patch", "应用邮件补丁", ["应用补丁", "git am"],
      [("git am *.patch", "应用 mbox 补丁")], "低", "进阶"),
    c("git apply", "g_patch", "应用 diff 补丁", ["应用补丁", "git apply"],
      [("git apply p.patch", "应用补丁")], "低", "日常", None, "apply 不动提交；am 会创建提交"),
    c("git send-email", "g_patch", "发送补丁邮件", ["发送邮件", "git send-email"],
      [("git send-email *.patch", "发到邮件列表")], "低", "进阶"),
    c("git imap-send", "g_patch", "经 IMAP 发补丁", ["IMAP发送", "git imap-send"],
      [("git imap-send *.patch", "通过 IMAP 发送")], "低", "进阶"),
    c("git mailinfo", "g_patch", "提取邮件补丁信息", ["邮件信息", "git mailinfo"],
      [("git mailinfo msg patch < m", "解析邮件")], "低", "进阶"),

    # ---- 调试 ----
    c("git bisect", "g_debug", "二分定位引入问题的提交", ["二分查找", "git bisect"],
      [("git bisect start", "开始"), ("git bisect bad/good <sha>", "标记"), ("git bisect run ./test.sh", "自动")], "低", "进阶"),

    # ---- 维护 ----
    c("git gc", "g_maint", "垃圾回收", ["垃圾回收", "git gc"],
      [("git gc", "压缩对象")], "低", "日常"),
    c("git fsck", "g_maint", "检查对象库", ["检查", "git fsck"],
      [("git fsck", "校验完整性")], "低", "进阶"),
    c("git prune", "g_maint", "删除不可达对象", ["清理", "git prune"],
      [("git prune", "删悬空对象")], "低", "进阶"),
    c("git repack", "g_maint", "重新打包对象", ["重新打包", "git repack"],
      [("git repack -ad", "打包并删冗余")], "低", "进阶"),
    c("git maintenance", "g_maint", "后台维护", ["维护", "git maintenance"],
      [("git maintenance start", "开启定时维护")], "低", "日常"),
    c("git count-objects", "g_maint", "统计对象", ["统计", "git count-objects"],
      [("git count-objects -v", "详细统计")], "低", "日常"),

    # ---- 脚本与其他 ----
    c("git archive", "g_other", "导出快照", ["导出", "git archive"],
      [("git archive --format=zip HEAD > t.zip", "导出当前")], "低", "日常"),
    c("git ls-files", "g_other", "列出跟踪文件", ["列出文件", "git ls-files"],
      [("git ls-files", "看已跟踪文件")], "低", "日常"),
    c("git rev-parse", "g_other", "解析修订/路径", ["解析", "git rev-parse"],
      [("git rev-parse HEAD", "得完整 SHA"), ("git rev-parse --show-toplevel", "仓库根")], "低", "进阶"),
    c("git rev-list", "g_other", "列出提交对象", ["列出提交", "git rev-list"],
      [("git rev-list --count HEAD", "提交数")], "低", "进阶"),

    # ---- 底层命令 plumbing ----
    c("git cat-file", "g_plumb", "查看对象内容/类型", ["对象查看", "git cat-file"],
      [("git cat-file -p <sha>", "看对象内容"), ("git cat-file -t <sha>", "看类型")], "低", "进阶"),
    c("git hash-object", "g_plumb", "计算/写入对象哈希", ["哈希", "git hash-object"],
      [("git hash-object f.txt", "得 SHA-1")], "低", "进阶"),
    c("git update-index", "g_plumb", "操作索引", ["索引", "git update-index"],
      [("git update-index --add f", "加入索引")], "低", "进阶"),
    c("git write-tree", "g_plumb", "把索引写成树对象", ["写树", "git write-tree"],
      [("git write-tree", "生成树 SHA")], "低", "进阶"),
    c("git commit-tree", "g_plumb", "创建提交对象", ["创建提交", "git commit-tree"],
      [("git commit-tree <tree> -p <parent> -m 'm'", "造提交")], "低", "进阶"),
    c("git update-ref", "g_plumb", "更新引用", ["更新引用", "git update-ref"],
      [("git update-ref refs/heads/x <sha>", "设分支指向")], "低", "进阶"),
    c("git show-ref", "g_plumb", "列出引用", ["列出引用", "git show-ref"],
      [("git show-ref", "看所有引用")], "低", "进阶"),
    c("git symbolic-ref", "g_plumb", "读写符号引用", ["符号引用", "git symbolic-ref"],
      [("git symbolic-ref HEAD refs/heads/main", "设 HEAD")], "低", "进阶"),
    c("git name-rev", "g_plumb", "把 SHA 映射为引用名", ["名称映射", "git name-rev"],
      [("git name-rev <sha>", "得分支/标签名")], "低", "进阶"),
    c("git for-each-ref", "g_plumb", "迭代引用", ["引用迭代", "git for-each-ref"],
      [("git for-each-ref --format='%(refname)'", "列引用")], "低", "进阶"),
    c("git verify-pack", "g_plumb", "校验 pack 文件", ["校验pack", "git verify-pack"],
      [("git verify-pack -v f.pack", "详细校验")], "低", "进阶"),
    c("git pack-objects", "g_plumb", "打包对象", ["打包对象", "git pack-objects"],
      [("git pack-objects out < objs", "生成 pack")], "低", "进阶"),
    c("git index-pack", "g_plumb", "建 pack 索引", ["pack索引", "git index-pack"],
      [("git index-pack f.pack", "生成 idx")], "低", "进阶"),
    c("git unpack-objects", "g_plumb", "解包到对象库", ["解包", "git unpack-objects"],
      [("git unpack-objects < f.pack", "解包")], "低", "进阶"),
    c("git pack-refs", "g_plumb", "打包引用", ["打包引用", "git pack-refs"],
      [("git pack-refs --all", "压缩 refs")], "低", "进阶"),
    c("git read-tree", "g_plumb", "读树到索引", ["读树", "git read-tree"],
      [("git read-tree <tree>", "载入索引")], "低", "进阶"),
    c("git ls-tree", "g_plumb", "列树对象内容", ["列树", "git ls-tree"],
      [("git ls-tree HEAD", "看根树")], "低", "进阶"),
    c("git mktree", "g_plumb", "由 ls-tree 输出建树", ["建树", "git mktree"],
      [("git ls-tree HEAD | git mktree", "重建树")], "低", "进阶"),
    c("git notes", "g_plumb", "给提交加附注", ["附注", "git notes"],
      [("git notes add -m 'x' <sha>", "加注")], "低", "进阶"),
    c("git replace", "g_plumb", "替换对象", ["替换对象", "git replace"],
      [("git replace <sha> <sha2>", "临时替换")], "低", "进阶"),

    # ---- 进阶工作流 ----
    c("git filter-repo", "g_adv", "重写历史（推荐）", ["重写历史", "git filter-repo"],
      [("git filter-repo --path dir/", "只保留某目录历史")], "低", "进阶",
      "破坏性操作，先备份；取代已弃用 filter-branch"),
    c("git filter-branch", "g_adv", "重写历史（已弃用）", ["重写历史", "git filter-branch"],
      [("git filter-branch --tree-filter '...' HEAD", "改写")], "低", "进阶",
      "已弃用，优先 filter-repo；慢且易错"),
    c("git subtree", "g_adv", "子树合并", ["子树", "git subtree"],
      [("git subtree add --prefix=lib url", "嵌入子项目")], "低", "进阶"),
    c("git sparse-checkout", "g_adv", "稀疏检出", ["稀疏检出", "git sparse-checkout"],
      [("git sparse-checkout set src/", "只检某目录")], "低", "进阶"),
    c("git rerere", "g_adv", "重用冲突解决", ["重用解决", "git rerere"],
      [("git config rerere.enabled true", "开启")], "低", "进阶"),
    c("git instaweb", "g_adv", "启动 Web 界面", ["web界面", "git instaweb"],
      [("git instaweb", "本地起 gitweb")], "低", "日常"),
    c("git credential", "g_adv", "凭证管理", ["凭证", "git credential"],
      [("git config credential.helper store", "明文存密码")], "低", "日常",
      "store 明文存密码不安全，推荐 cache/osxkeychain"),
    c("git fast-export", "g_adv", "导出为流", ["导出流", "git fast-export"],
      [("git fast-export --all", "导出供迁移")], "低", "进阶"),
    c("git fast-import", "g_adv", "从流导入", ["导入流", "git fast-import"],
      [("git fast-import < stream", "导入")], "低", "进阶"),

    # ---- 传输与服务 ----
    c("git daemon", "g_transport", "匿名 Git 服务", ["git服务", "git daemon"],
      [("git daemon --base-path=/repos", "起只读服务")], "低", "进阶"),
    c("git upload-pack", "g_transport", "上传对象（拉取端）", ["上传", "git upload-pack"],
      [("git upload-pack repo", "被 fetch 调用")], "低", "进阶"),
    c("git receive-pack", "g_transport", "接收对象（推送端）", ["接收", "git receive-pack"],
      [("git receive-pack repo", "被 push 调用")], "低", "进阶"),
    c("git http-backend", "g_transport", "CGI 智能 HTTP", ["http后端", "git http-backend"],
      [("git http-backend", "配合 web 服务器")], "低", "进阶"),
    c("git send-pack", "g_transport", "推送引用", ["推送", "git send-pack"],
      [("git send-pack origin main", "底层 push")], "低", "进阶"),
    c("git shell", "g_transport", "受限登录 shell", ["受限shell", "git shell"],
      [("git shell", "仅允许 git 操作")], "低", "进阶"),
    c("git upload-archive", "g_transport", "支持 git archive 远程", ["archive远程", "git upload-archive"],
      [("git upload-archive repo", "配合 archive")], "低", "进阶"),
]


def main():
    data = {"categories": CATEGORIES, "commands": LINUX + GIT}
    json_path = os.path.join(DATA_DIR, "commands.json")
    js_path = os.path.join(DATA_DIR, "commands.js")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("window.COMMAND_DATA = ")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write(";")
    linux_n = sum(1 for x in data["commands"] if x["category"] in {c["id"] for c in CATEGORIES if c["group"] == "linux"})
    git_n = sum(1 for x in data["commands"] if x["category"] in {c["id"] for c in CATEGORIES if c["group"] == "git"})
    print("OK ->", json_path)
    print("Linux 命令数:", linux_n)
    print("Git   命令数:", git_n)
    print("合计:", len(data["commands"]))


if __name__ == "__main__":
    main()
